### ISSUE TITLE
[小米路由器3G]TinyProxy无法启动

### ISSUE THREAD

**Issue by AzureUni** [monlor/MIXBOX#1]
小米路由器3G
系统版本2.25.122

配置过程如下：
00. 返回主菜单
01. tinyproxy	[未运行] 

请输入你的选择：01
********* TinyProxy ***********
[轻量级的Http代理工具]
启动tinyproxy服务[1/0] [回车即1]：1
修改tinyproxy端口号(8888)？[1/0] 0
请输入tinyproxy外网访问配置[1/0][回车即1]：1
【TinyProxy】: 正在停止tinyproxy服务... 
【TinyProxy】: 删除nat-start触发...
【TinyProxy】: 正在启动tinyproxy服务... 
【TinyProxy】: 添加nat-start触发事件...
【TinyProxy】: 启动tinyproxy服务完成！

按任意键返回.

返回后进入已安装插件选单后仍显示为未运行。

**Comment by ZhuojingXie** [comment]
感谢作者。一直再弄monlor 的回国模式，无果。偶然间发现了新的更新变成了mixbox。没想到已经消除了bug。谢谢
