### ISSUE TITLE
两个源内容都是404

### ISSUE THREAD

**Issue by kanlidy** [monlor/MIXBOX#100]
coding下载源地址改为https://monlor.coding.net/p/mbfiles/d/mbfiles/git/raw/master
github下载源地址改为https://raw.githubusercontent.com/monlor/mbfiles/master

请注意，谢谢！

**Comment by monlor** [comment]
404是正常的，这个地址无法列出文件列表，尝试访问`https://monlor.coding.net/p/mbfiles/d/mbfiles/git/raw/master/install.sh`

**Comment by abcfy2** [comment]
@monlor 发现一个神级github的镜像： https://www.jsdelivr.com/ 我已经把我的脚本中的`raw.githubusercontent.com`的链接全部替换成了`https://cdn.jsdelivr.net/gh/`，速度杠杠的，再也不用搞双仓库了

**Comment by lirui117974** [comment]
> 
> 
> coding下载源地址改为https://monlor.coding.net/p/mbfiles/d/mbfiles/git/raw/master
> github下载源地址改为https://raw.githubusercontent.com/monlor/mbfiles/master
> 
> 请注意，谢谢！

这个是在mixbox里面的管理工具里面，更换工具箱下载源，选中下载源
还是需要在某个文件里面重新改掉url 如果是需要在文件里面改 有没有教程？
