### ISSUE TITLE
EasyExplorer插件无法启动

### ISSUE THREAD

**Issue by yaio** [monlor/MIXBOX#101]
![image](https://user-images.githubusercontent.com/20538860/75885112-e5977080-5e60-11ea-8d61-bf53015bd853.png)

输入配置后最后会报以下错误：
/etc/mixbox/apps/easyexplorer/scripts/easyexplorer.sh: source: line 2: can't open '/etc/mixbox/bin/bas'
/etc/mixbox/apps/easyexplorer/scripts/easyexplorer.sh: source: line 2: can't open '/etc/mixbox/bin/bas'

**Comment by monlor** [comment]
已修复，顺便更新了二进制版本

**Comment by yaio** [comment]
非常感谢！
