### ISSUE TITLE
frps启动还是有问题

### ISSUE THREAD

**Issue by blackhumors** [monlor/MIXBOX#102]
我发现启动的时候难得有一次可以，ps | grep frps看了也没有对应进程，大佬再看看呢，现在又启动不起来了，配置都是初始化配置

**Comment by blackhumors** [comment]
现象好像是这样的，命令行操作启动后很长一段时间内状态一直是未启动，也没有对应进程，我是过了一小时上去看又显示成功了，ps | grep能找到对应的进程了

**Comment by monlor** [comment]
1.过一小时能成功可能是工具箱守护进程帮你启动了
2.尝试关闭frps，手动执行命令`/etc/mixbox/apps/frps/bin/frps -c /etc/mixbox/apps/frps/config/f
rps.conf`，检查服务是否正常

**Comment by blackhumors** [comment]
仍然不行
![image](https://user-images.githubusercontent.com/20552372/75942986-cc2d0d80-5ece-11ea-94e1-81b412075b09.png)

**Comment by monlor** [comment]
你可以尝试下载这个frp程序`https://github.com/fatedier/frp/releases/download/v0.31.2/frp_0.31.2_linux_arm.tar.gz`，替换其中的frps到工具箱目录`/etc/mixbox/apps/frps/bin`，如果能执行成功我就更新一下版本

**Comment by monlor** [comment]
替换完成后直接用`mixbox `命令重启`frps`，并查看状态

**Comment by blackhumors** [comment]
更换了好了，谢谢

**Comment by blackhumors** [comment]
![image](https://user-images.githubusercontent.com/20552372/75947961-10270f00-5edd-11ea-9350-0082a563c740.png)
手动更新工具箱解压失败

**Comment by blackhumors** [comment]
还有如何手动更换下载源

**Comment by monlor** [comment]
`frps`启动成功了么？我刚才试了一下更新没有问题，如果你多次尝试还有问题的话，执行下面这个命令，把运行的日志发给我。`sh -xc "$(curl -kfsSl https://cdn.jsdelivr.net/gh/monlor/MIXBOX@master/apps/mixbox/scripts/update.sh)" && source /etc/profile &> /dev/null`

**Comment by blackhumors** [comment]
frps更换你给的包后后可以了，更新还是不行
![image](https://user-images.githubusercontent.com/20552372/75952818-cd6c3380-5eea-11ea-8b4a-d305a19de997.png)

**Comment by blackhumors** [comment]
现在执行你发的更新脚本不报错了，但是为什么版本还是0.0.6，而且也看不到readme里面说的新增加的插件

**Comment by monlor** [comment]
已更新frps到最新版本
