### ISSUE TITLE
[Bug Report] 新装后显示没有插件可安装

### ISSUE THREAD

**Issue by helfee** [monlor/MIXBOX#103]
**Bug 详情**
如题

**你的操作**
刚安装的mixbox,一个插件都没装..

**屏幕截图**

***************************************
     *****   MIXBOX 工具箱   *****
***************************************
当前版本：[0.1.9.1]     最新版本：[获取中]
设备型号：[R2D]         核心温度：[65°C]
***************************************
00. 返回主菜单
[已经没有插件可安装了哦！]

请输入你的选择：

**日志信息**

```
```

**Comment by CoderJ** [comment]
+1

**Comment by helfee** [comment]
已经正常了,感谢作者的劳动!
