### ISSUE TITLE
版本0.1.9.1 无法下载插件

### ISSUE THREAD

**Issue by lirui117974** [monlor/MIXBOX#104]
**Bug 详情**
我用这个地址下载mixbox 0.0.6
sh -c "$(curl -kfsSl https://dev.tencent.com/u/monlor/p/MIXBOX/git/raw/master/install.sh)" && source /etc/profile &> /dev/null
可以安装插件

但是我用这个地址下载mixbox 0.1.9.1
sh -c "$(curl -kfsSl https://monlor.coding.net/p/mbfiles/d/mbfiles/git/raw/master/install.sh)" && source /etc/profile &> /dev/null
下载插件总是失败

我看到说下载源更改了
coding下载源地址改为https://monlor.coding.net/p/mbfiles/d/mbfiles/git/raw/master
github下载源地址改为https://raw.githubusercontent.com/monlor/mbfiles/master

这个是在mixbox里面的管理工具里面，更换工具箱下载源，选中下载源
还是需要在某个文件里面重新改掉url 如果是需要在文件里面改 有没有教程？

**Comment by monlor** [comment]
已修复
