### ISSUE TITLE
[Bug Report] 0.1.9.3 无法安装Shadowsocks，报错 工具箱版本过低！【shadowsocks】要求工具箱版本：0.0.1

### ISSUE THREAD

**Issue by CoderJ** [monlor/MIXBOX#106]
**Bug 详情**

0.1.9.3 无法安装Shadowsocks，报错 ：

请输入你的选择：22
确定要安装shadowsocks插件？[1/0] 1
【Tools】: 开始安装【shadowsocks】插件...
【Tools】: 下载插件安装文件...
【Tools】: 解压安装文件...
【Tools】: 赋予可执行文件...
【Tools】: 处理器架构符合安装要求
【Tools】: 检查工具箱版本...
sort: invalid option -- V
BusyBox v1.19.4 (2018-10-29 07:52:03 UTC) multi-call binary.

Usage: sort [-nru] [FILE]...

Sort lines of text

	-n	Sort numbers
	-r	Reverse sort order
	-u	Suppress duplicate lines

【Tools】: 工具箱版本过低！【shadowsocks】要求工具箱版本：0.0.1
【Tools】: 插件【shadowsocks】安装失败！清理文件...

**Comment by monlor** [comment]
现在再试试呢

**Comment by monlor** [comment]
先关闭了，有问题在提
