### ISSUE TITLE
小米路由 R2D 安装了新增的npc无法使用

### ISSUE THREAD

**Issue by helfee** [monlor/MIXBOX#107]
看到有新程序就赶紧部署了测试 ,一直无法启动,在 /etc/mixbox/apps/npc/bin 直接执行 npc报错 ,后来到官网下载了几个不同版本的 client 尝试 , linux_arm_v5_client 可以使用 ,替换源文件后能正常启动了 ,麻烦看看什么原因

**Comment by monlor** [comment]
已修复
