### ISSUE TITLE
frps配置路径错误

### ISSUE THREAD

**Issue by blackhumors** [monlor/MIXBOX#108]
***************************************
     *****   MIXBOX 工 具 箱    *****
***************************************
当 前 版 本 ： [0.1.9.4]     最 新 版 本 ： [0.1.9.4]
设 备 型 号 ： [R1D]         核 心 温 度 ： [86°C]
***************************************
00. 返 回 主 菜 单
01. koolproxy   [运 行 模 式 : 视 频 模 式 , 规 则 : 2020-02-27 23:00]
02. frps        [未 运 行 ]
03. smartdns    [未 运 行 ]
04. firewall    [未 运 行 ]

请 输 入 你 的 选 择 ： 2
/etc/mixbox/bin/mixbox: source: line 480: can't open '/etc/mixbox/apps/frps/config/
mixbox.conf'
root@XiaoQiang:~#

**Comment by monlor** [comment]
已修复
