### ISSUE TITLE
frps无法启动

### ISSUE THREAD

**Issue by blackhumors** [monlor/MIXBOX#109]
frps配置完还是不启动，和之前反馈的问题一样

**Comment by monlor** [comment]
无法重现

**Comment by blackhumors** [comment]
root@XiaoQiang:/userdisk/data/frp_0.31.2_linux_arm# ls -l frps
-rwxrwxr-x    1 1000     1000      10027008 Feb  4 22:16 frps
root@XiaoQiang:/userdisk/data/frp_0.31.2_linux_arm# ls -l /etc/mixbox/apps/frps/bin
/frps
-rwxr-xr-x    1 root     root       3915352 Mar  7 10:46 /etc/mixbox/apps/frps/bin/
frps

**Comment by blackhumors** [comment]
上面的是我用你之前给的链接下载的，下面的是mixbox里的，好像大小不一样，不是同一个？

**Comment by monlor** [comment]
工具箱里面的frps是用upx压缩了的，我发一个不压缩的你试试

**Comment by blackhumors** [comment]
替换了就一切正常

**Comment by blackhumors** [comment]
好的，你发我地址吧

**Comment by monlor** [comment]
已经更新版本了

**Comment by blackhumors** [comment]
这个没解压缩的版本就是我上面下载的吧，大小都一样，使用也没问题
