### ISSUE TITLE
SmartDNS Port 535

### ISSUE THREAD

**Issue by liliass** [monlor/MIXBOX#113]
请问，Port535  要去哪里转发 /设置 ？ 

MacBook-Pro ~ % nslookup www.baidu.com
Server:		192.168.31.1
Address:	192.168.31.1#53

Non-authoritative answer:
www.baidu.com	canonical name = www.a.shifen.com.
Name:	www.a.shifen.com
Address: 112.80.248.76
Name:	www.a.shifen.com
Address: 112.80.248.75

**Comment by scetus** [comment]
同样想问这个问题

我都设置好了，但不知道怎么具体设置。看网上的说明，都是有web界面的。

**Comment by monlor** [comment]
不用设置转发，默认是配置dnsmasq上游dns
