### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by Psychiwave** [monlor/MIXBOX#116]
**Bug 详情**
输入完命令一键安装后试图打开mixbox

**屏幕截图**

![image](https://user-images.githubusercontent.com/32756978/76698434-cbba2100-66dd-11ea-9421-4ba21a652200.png)

**日志信息**
-ash: mixbox: not found

```
```

**Comment by monlor** [comment]
希望能提供更多的安装信息

**Comment by rakaki** [comment]
我也遇到了这个问题。请问你解决了吗
