### ISSUE TITLE
vsftp无法启动

### ISSUE THREAD

**Issue by Chengliangxing** [monlor/MIXBOX#12]
按任意键返回.【VsFtpd】: 正在启动vsftpd服务...
【VsFtpd】: 加载vsftpd设置...
【VsFtpd】: 添加nat-start触发事件...
【VsFtpd】: 启动vsftpd服务完成！
***************************************
     *****   MIXBOX 工具箱   *****
***************************************
当前版本：[0.0.6]       最新版本：[0.0.6]
设备型号：[R3P]         上网方式：[pppoe]
***************************************
00. 返回主菜单
01. vsftpd      [未运行]
02. entware     [安装路径: /extdisks/sda1/.Entware]

vsftp设置完成，但是无法启动。
之前用misstar工具箱也是无法启动。

**Comment by monlor** [comment]
vsftp没发完美支持所有型号
