### ISSUE TITLE
[Bug Report]tinyproy不能正常启动

### ISSUE THREAD

**Issue by refactor2** [monlor/MIXBOX#122]
**Bug 详情**
路由器：R3
tinyproy不能正常启动

**你的操作**
按照提示安装，启动

**日志信息**
/etc/mixbox/apps/tinyproxy/bin/tinyproxy: can't load library 'libresolv.so.0'

```
```

**Comment by monlor** [comment]
程序在mipsle设备上可能用问题，没有时间去交叉编译程序，暂时先放弃这个工具吧
