### ISSUE TITLE
[Bug Report] zerotier config missing option 'networkid'

### ISSUE THREAD

**Issue by jsfaint** [monlor/MIXBOX#123]
**Bug 详情**

zerotier启动完成之后，下次重开机服务没有自动启动

**解决方案**
在`/etc/mixbox/mbdb/zerotier`里面增加如下option之后就正常了
```
option networkid ''
```

**Comment by monlor** [comment]
这个不应该啊，刚配置好zerotier的时候networkid是存在的么

**Comment by jsfaint** [comment]
> 这个不应该啊，刚配置好zerotier的时候networkid是存在的么
不存在

卸载重装了zerotier，删除了mbdb里面的zerotier配置之后打开zerotier，会出现如图提示
![image](https://user-images.githubusercontent.com/571829/79058815-32166d00-7ca5-11ea-9408-0e95a50b2940.png)

但是此时zerotier显示启动成功了，在zerotier central里面显示也是在线
![image](https://user-images.githubusercontent.com/571829/79058840-6ab64680-7ca5-11ea-98f3-424237019ca3.png)

此时查看mbdb里面的zerotier配置，可以看到没有networkid这个option
![image](https://user-images.githubusercontent.com/571829/79058847-891c4200-7ca5-11ea-9ab7-75779d410dcb.png)

路由器重启之后就会因为没有networkid，zerotier启动失败

**Comment by monlor** [comment]
这是因为你没有设置网络id，修改网络id那里要输入1，然后再输入网络id。这个选项后面我打得问好，而不是冒号。

**Comment by jsfaint** [comment]
> 这是因为你没有设置网络id，修改网络id那里要输入1，然后再输入网络id。这个选项后面我打得问好，而不是冒号。

图里我把networkid马赛克掉了……

**Comment by monlor** [comment]
那里要输入1，而不是networkid

**Comment by jsfaint** [comment]
> 那里要输入1，而不是networkid

明白了，所以是提示有一些歧义
谢谢
