### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by PatDMark** [monlor/MIXBOX#124]
**Bug 详情**

正常安装完毕 Entware后安装Shadowsocks，启用Entware后，在shadowsocks中添加SSR订阅时，无法获得订阅中的节点，获取到的数量为0，并且提示 Illegal instruction (core dumped)

详细的屏幕显示内容为下：
********* ShadowSocks ***********
[最好的翻墙工具，没有之一，还可以加速国内外游戏]
启动shadowsocks服务[1/0] [回车即1]：1
添加shadowsocks节点？[1/0] 1
选择添加方式[1.手动添加 2.订阅地址 3.uri地址] 2
清空订阅地址列表后再添加？[1/0] 1
请输入ssr节点订阅地址(回车停止添加)：https://dripcloud.ga/link/FDbSMMCYqcobrs06
请输入ssr节点订阅地址(回车停止添加)：
在线更新ssr订阅节点...
【ShadowSocks】: 更新订阅地址：https://dripcloud.ga/link/FDbSMMCYqcobrs06
【ShadowSocks】: 第1次下载节点...
Illegal instruction (core dumped)
是否需要删除所有的订阅节点？[1/0] 

**你的操作**

**屏幕截图**

**日志信息**

在目录下无任何日志信息
```
```

**Comment by baofaguo** [comment]
我也是 Illegal instruction (core dumped)

**Comment by monlor** [comment]
#127
