### ISSUE TITLE
插件不能安装了

### ISSUE THREAD

**Issue by yangyuw** [monlor/MIXBOX#126]
**Bug 详情**

确定要安装aliddns插件？[1/0] 1
【Tools】: 开始安装【aliddns】插件...
【Tools】: 下载插件安装文件...
【Tools】: 解压安装文件...
【Tools】: 文件解压失败！

**Comment by baofaguo** [comment]
我也是这样

**Comment by Richard-Zheng** [comment]
同样情况，并且无法卸载工具箱。

**Comment by tomswatermelon** [comment]
同样情况，突然就这样了，很奇怪

**Comment by Faintabc** [comment]
进入命令界面，找到工具箱管理，找更新工具箱，选择更换源地址那个，然后粘贴https://monlor.coding.net/p/mbfiles/d/mbfiles/git/raw/master
就可以了

**Comment by monlor** [comment]
抱歉，手动换源我虽然写在更新日志里了，但是没有在README里重点强调，很多人还不知道，楼上的操作完全正确。
