### ISSUE TITLE
[Bug Report]Illegal instruction。小米路由器R2D

### ISSUE THREAD

**Issue by baofaguo** [monlor/MIXBOX#127]
**Bug 详情**

**你的操作**

**屏幕截图**

**日志信息**

```
```
【ShadowSocks】: 关闭ss主进程...
【ShadowSocks】: 删除nat-start触发...
【ShadowSocks】: 清除iptables规则...
【ShadowSocks】: 创建节点配置文件...
【ShadowSocks】: 检测v2ray版本，本地版本：，在线版本：4.9.0
【ShadowSocks】: 版本不一致，正在更新...
【ShadowSocks】: 生成V2Ray配置文件...
【ShadowSocks】: 启动代理为v2ray，测试配置文件
【ShadowSocks】: 启动v2ray主进程(usbl3c.zhs.one)...
【ShadowSocks】: 游戏加速使用v2ray代理模式！
【ShadowSocks】: 创建ipset规则...
【ShadowSocks】: 加载iptables的nat规则...
【ShadowSocks】: 添加国外黑名单规则...
【ShadowSocks】: 加载iptables的udp规则...
【ShadowSocks】: 加载ACL规则:[MI9-baofa]代理模式为:[科学上网][游戏加速]
【ShadowSocks】: 加载ACL规则:[其余主机]代理模式为:[不走代理][不走游戏]
【ShadowSocks】: 开启dns2socks进程...
【ShadowSocks】: 启用DNS重定向到192.168.31.1
Illegal instruction (core dumped)
【ShadowSocks】: 添加nat-start触发事件...
【ShadowSocks】: 启动shadowsocks服务完成，启动失败可查看日志或多次重试！

**Comment by abcfy2** [comment]
我定位了一下，应该是/etc/mixbox/bin/base64这个文件编译的有问题。感觉作者的目的是想升级base64这条命令，但是静态编译之后可能某些参数不对劲，导致执行的时候偶尔就会出现core dump

**Comment by abcfy2** [comment]
我自己用小米路由器R2D的工具链编译了一下coreutils，上传base64到路由器覆盖了这个文件，结果一堆运行错误：

```
【ShadowSocks】: 关闭ss主进程...
【ShadowSocks】: 删除nat-start触发...
base64: invalid input
base64: invalid input
base64: invalid input
【ShadowSocks】: 清除iptables规则...
【ShadowSocks】: 启动kcptun加速主进程(gate.fengyu.io)...
【ShadowSocks】: 创建节点配置文件...
【ShadowSocks】: 启动ss主进程(gate.fengyu.io)...
【ShadowSocks】: 创建ipset规则...
【ShadowSocks】: 加载iptables的nat规则...
【ShadowSocks】: 添加国外黑名单规则...
【ShadowSocks】: 加载ACL规则:[全部主机]代理模式为:[科学上网]
【ShadowSocks】: 启动ss-local本地socks5代理...
【ShadowSocks】: 开启dns2socks进程...
sh: cGRhdGUuc2g: unknown operand
Usage: uci [<options>] <command> [<arguments>]

Commands:
        batch
        export     [<config>]
        import     [<config>]
        changes    [<config>]
        commit     [<config>]
        add        <config> <section-type>
        add_list   <config>.<section>.<option>=<string>
        del_list   <config>.<section>.<option>=<string>
        show       [<config>[.<section>[.<option>]]]
        get        <config>.<section>[.<option>]
        set        <config>.<section>[.<option>]=<value>
        delete     <config>[.<section>[[.<option>][=<id>]]]
        rename     <config>.<section>[.<option>]=<name>
        revert     <config>[.<section>[.<option>]]
        reorder    <config>.<section>=<position>

Options:
        -c <path>  set the search path for config files (default: /etc/config)
        -d <str>   set the delimiter for list values in uci show
        -f <file>  use <file> as input instead of stdin
        -m         when importing, merge data into an existing package
        -n         name unnamed sections on export (default)
        -N         don't name unnamed sections
        -p <path>  add a search path for config change files
        -P <path>  add a search path for config change files and use as default
        -q         quiet mode (don't print error messages)
        -s         force strict mode (stop on parser errors, default)
        -S         disable strict mode
        -X         do not use extended syntax on 'show'

Usage: uci [<options>] <command> [<arguments>]

Commands:
        batch
        export     [<config>]
        import     [<config>]
        changes    [<config>]
        commit     [<config>]
        add        <config> <section-type>
        add_list   <config>.<section>.<option>=<string>
        del_list   <config>.<section>.<option>=<string>
        show       [<config>[.<section>[.<option>]]]
        get        <config>.<section>[.<option>]
        set        <config>.<section>[.<option>]=<value>
        delete     <config>[.<section>[[.<option>][=<id>]]]
        rename     <config>.<section>[.<option>]=<name>
        revert     <config>[.<section>[.<option>]]
        reorder    <config>.<section>=<position>

Options:
        -c <path>  set the search path for config files (default: /etc/config)
        -d <str>   set the delimiter for list values in uci show
        -f <file>  use <file> as input instead of stdin
        -m         when importing, merge data into an existing package
        -n         name unnamed sections on export (default)
        -N         don't name unnamed sections
        -p <path>  add a search path for config change files
        -P <path>  add a search path for config change files and use as default
        -q         quiet mode (don't print error messages)
        -s         force strict mode (stop on parser errors, default)
        -S         disable strict mode
        -X         do not use extended syntax on 'show'

Usage: uci [<options>] <command> [<arguments>]

Commands:
        batch
        export     [<config>]
        import     [<config>]
        changes    [<config>]
        commit     [<config>]
        add        <config> <section-type>
        add_list   <config>.<section>.<option>=<string>
        del_list   <config>.<section>.<option>=<string>
        show       [<config>[.<section>[.<option>]]]
        get        <config>.<section>[.<option>]
        set        <config>.<section>[.<option>]=<value>
        delete     <config>[.<section>[[.<option>][=<id>]]]
        rename     <config>.<section>[.<option>]=<name>
        revert     <config>[.<section>[.<option>]]
        reorder    <config>.<section>=<position>

Options:
        -c <path>  set the search path for config files (default: /etc/config)
        -d <str>   set the delimiter for list values in uci show
        -f <file>  use <file> as input instead of stdin
        -m         when importing, merge data into an existing package
        -n         name unnamed sections on export (default)
        -N         don't name unnamed sections
        -p <path>  add a search path for config change files
        -P <path>  add a search path for config change files and use as default
        -q         quiet mode (don't print error messages)
        -s         force strict mode (stop on parser errors, default)
        -S         disable strict mode
        -X         do not use extended syntax on 'show'

base64: invalid input
sh: ZV91cGRhdGUuc2g: unknown operand
Usage: uci [<options>] <command> [<arguments>]

Commands:
        batch
        export     [<config>]
        import     [<config>]
        changes    [<config>]
        commit     [<config>]
        add        <config> <section-type>
        add_list   <config>.<section>.<option>=<string>
        del_list   <config>.<section>.<option>=<string>
        show       [<config>[.<section>[.<option>]]]
        get        <config>.<section>[.<option>]
        set        <config>.<section>[.<option>]=<value>
        delete     <config>[.<section>[[.<option>][=<id>]]]
        rename     <config>.<section>[.<option>]=<name>
        revert     <config>[.<section>[.<option>]]
        reorder    <config>.<section>=<position>

Options:
        -c <path>  set the search path for config files (default: /etc/config)
        -d <str>   set the delimiter for list values in uci show
        -f <file>  use <file> as input instead of stdin
        -m         when importing, merge data into an existing package
        -n         name unnamed sections on export (default)
        -N         don't name unnamed sections
        -p <path>  add a search path for config change files
        -P <path>  add a search path for config change files and use as default
        -q         quiet mode (don't print error messages)
        -s         force strict mode (stop on parser errors, default)
        -S         disable strict mode
        -X         do not use extended syntax on 'show'

Usage: uci [<options>] <command> [<arguments>]

Commands:
        batch
        export     [<config>]
        import     [<config>]
        changes    [<config>]
        commit     [<config>]
        add        <config> <section-type>
        add_list   <config>.<section>.<option>=<string>
        del_list   <config>.<section>.<option>=<string>
        show       [<config>[.<section>[.<option>]]]
        get        <config>.<section>[.<option>]
        set        <config>.<section>[.<option>]=<value>
        delete     <config>[.<section>[[.<option>][=<id>]]]
        rename     <config>.<section>[.<option>]=<name>
        revert     <config>[.<section>[.<option>]]
        reorder    <config>.<section>=<position>

Options:
        -c <path>  set the search path for config files (default: /etc/config)
        -d <str>   set the delimiter for list values in uci show
        -f <file>  use <file> as input instead of stdin
        -m         when importing, merge data into an existing package
        -n         name unnamed sections on export (default)
        -N         don't name unnamed sections
        -p <path>  add a search path for config change files
        -P <path>  add a search path for config change files and use as default
        -q         quiet mode (don't print error messages)
        -s         force strict mode (stop on parser errors, default)
        -S         disable strict mode
        -X         do not use extended syntax on 'show'

Usage: uci [<options>] <command> [<arguments>]

Commands:
        batch
        export     [<config>]
        import     [<config>]
        changes    [<config>]
        commit     [<config>]
        add        <config> <section-type>
        add_list   <config>.<section>.<option>=<string>
        del_list   <config>.<section>.<option>=<string>
        show       [<config>[.<section>[.<option>]]]
        get        <config>.<section>[.<option>]
        set        <config>.<section>[.<option>]=<value>
        delete     <config>[.<section>[[.<option>][=<id>]]]
        rename     <config>.<section>[.<option>]=<name>
        revert     <config>[.<section>[.<option>]]
        reorder    <config>.<section>=<position>

Options:
        -c <path>  set the search path for config files (default: /etc/config)
        -d <str>   set the delimiter for list values in uci show
        -f <file>  use <file> as input instead of stdin
        -m         when importing, merge data into an existing package
        -n         name unnamed sections on export (default)
        -N         don't name unnamed sections
        -p <path>  add a search path for config change files
        -P <path>  add a search path for config change files and use as default
        -q         quiet mode (don't print error messages)
        -s         force strict mode (stop on parser errors, default)
        -S         disable strict mode
        -X         do not use extended syntax on 'show'

base64: invalid input
sh: cy5zaCByZXN0YXJ0: unknown operand
Usage: uci [<options>] <command> [<arguments>]

Commands:
        batch
        export     [<config>]
        import     [<config>]
        changes    [<config>]
        commit     [<config>]
        add        <config> <section-type>
        add_list   <config>.<section>.<option>=<string>
        del_list   <config>.<section>.<option>=<string>
        show       [<config>[.<section>[.<option>]]]
        get        <config>.<section>[.<option>]
        set        <config>.<section>[.<option>]=<value>
        delete     <config>[.<section>[[.<option>][=<id>]]]
        rename     <config>.<section>[.<option>]=<name>
        revert     <config>[.<section>[.<option>]]
        reorder    <config>.<section>=<position>

Options:
        -c <path>  set the search path for config files (default: /etc/config)
        -d <str>   set the delimiter for list values in uci show
        -f <file>  use <file> as input instead of stdin
        -m         when importing, merge data into an existing package
        -n         name unnamed sections on export (default)
        -N         don't name unnamed sections
        -p <path>  add a search path for config change files
        -P <path>  add a search path for config change files and use as default
        -q         quiet mode (don't print error messages)
        -s         force strict mode (stop on parser errors, default)
        -S         disable strict mode
        -X         do not use extended syntax on 'show'

Usage: uci [<options>] <command> [<arguments>]

Commands:
        batch
        export     [<config>]
        import     [<config>]
        changes    [<config>]
        commit     [<config>]
        add        <config> <section-type>
        add_list   <config>.<section>.<option>=<string>
        del_list   <config>.<section>.<option>=<string>
        show       [<config>[.<section>[.<option>]]]
        get        <config>.<section>[.<option>]
        set        <config>.<section>[.<option>]=<value>
        delete     <config>[.<section>[[.<option>][=<id>]]]
        rename     <config>.<section>[.<option>]=<name>
        revert     <config>[.<section>[.<option>]]
        reorder    <config>.<section>=<position>

Options:
        -c <path>  set the search path for config files (default: /etc/config)
        -d <str>   set the delimiter for list values in uci show
        -f <file>  use <file> as input instead of stdin
        -m         when importing, merge data into an existing package
        -n         name unnamed sections on export (default)
        -N         don't name unnamed sections
        -p <path>  add a search path for config change files
        -P <path>  add a search path for config change files and use as default
        -q         quiet mode (don't print error messages)
        -s         force strict mode (stop on parser errors, default)
        -S         disable strict mode
        -X         do not use extended syntax on 'show'

Usage: uci [<options>] <command> [<arguments>]

Commands:
        batch
        export     [<config>]
        import     [<config>]
        changes    [<config>]
        commit     [<config>]
        add        <config> <section-type>
        add_list   <config>.<section>.<option>=<string>
        del_list   <config>.<section>.<option>=<string>
        show       [<config>[.<section>[.<option>]]]
        get        <config>.<section>[.<option>]
        set        <config>.<section>[.<option>]=<value>
        delete     <config>[.<section>[[.<option>][=<id>]]]
        rename     <config>.<section>[.<option>]=<name>
        revert     <config>[.<section>[.<option>]]
        reorder    <config>.<section>=<position>

Options:
        -c <path>  set the search path for config files (default: /etc/config)
        -d <str>   set the delimiter for list values in uci show
        -f <file>  use <file> as input instead of stdin
        -m         when importing, merge data into an existing package
        -n         name unnamed sections on export (default)
        -N         don't name unnamed sections
        -p <path>  add a search path for config change files
        -P <path>  add a search path for config change files and use as default
        -q         quiet mode (don't print error messages)
        -s         force strict mode (stop on parser errors, default)
        -S         disable strict mode
        -X         do not use extended syntax on 'show'

base64: invalid input
【ShadowSocks】: 添加nat-start触发事件...
【ShadowSocks】: 启动shadowsocks服务完成，启动失败可查看日志或多次重试！
```

疑似用了什么魔改版本的base64命令？还是等待作者解答下吧 @monlor

**Comment by baofaguo** [comment]
不用覆盖 作者的虽然报错 但不影响使用 
显示未运行 其实已经运行了

**Comment by abcfy2** [comment]
问题完美解决，定位了差不多两个小时，总算找到了问题。我差不多也理解作者的意图了。

TD;DR:

1. 删除`/etc/mixbox/bin/base64*`: `rm -f /etc/mixbox/bin/base64*`
2. 修改`/etc/mixbox/scripts/helper.sh`中的`base_encode`函数，将这一行: `echo -n "$*" | base64` 改为 `echo -n "$*" | base64 | tr -d '\n'`

问题解决。

Long Read:

我的猜测是这样的，因为太长的base64编码会自动换行，但是作者并不期望base64编码换行。

比如这样的:

```bash
# echo 'very very very very very very very very very very very very long line' | base64
dmVyeSB2ZXJ5IHZlcnkgdmVyeSB2ZXJ5IHZlcnkgdmVyeSB2ZXJ5IHZlcnkgdmVyeSB2ZXJ5IHZl
cnkgbG9uZyBsaW5lCg==
```

被折行了。

可能作者发现`base64`命令来源于`/bin/base64`，实际则是`busybox`的软连接，只提供最最最基础的base64编解码功能，并不提供类似于来自于`coreutils`包里的`base64 -w 0`这样的参数截断换行。于是作者搞了个非常复杂的方式，就是不知道搞了哪个魔改版本的base64来取消默认换行行为。

但是这个版本的`base64`编译又有点问题，在R2D运行就是经常会段错误。

所以我的解决方案非常简单，就是直接用`tr`删掉换行符就完事了。

另: R2D的`/usr/bin/base64`命令是来源于`coreutils`的，提供了`-w`参数，为了更加通用，不依赖`base64`命令的来源，所以还是采用了`tr`删掉换行符的方案

**Comment by abcfy2** [comment]
等会提交PR彻底修复这个问题。 @monlor

**Comment by monlor** [comment]
不好意思，每次增加新功能也很少人愿意测试，所以无法保证每台机器都完美运行，base64我是用的go版本的，为了编译方便，如果小米路由器内置base64的话，工具箱就不提供这个程序了。

**Comment by abcfy2** [comment]
如果用go的话小米应该用armv5那个工具链，因为小米R2D的那个CPU标记是`armv7l`，但是不支持浮点好像，所以必须降级到armv5工具链编译才能正常运行

**Comment by baofaguo** [comment]
> 问题完美解决，定位了差不多两个小时，总算找到了问题。我差不多也理解作者的意图了。
> 
> TL;DR:
> 
> 1. 删除`/etc/mixbox/bin/base64*`: `rm -f /etc/mixbox/bin/base64*`
> 2. 修改`/etc/mixbox/scripts/helper.sh`中的`base_encode`函数，将这一行: `echo -n "$*" | base64` 改为 `echo -n "$*" | base64 | tr -d '\n'`
> 
> 问题解决。
> 
> Long Read:
> 
> 我的猜测是这样的，因为太长的base64编码会自动换行，但是作者并不期望base64编码换行。
> 
> 比如这样的:
> 
> ```shell
> # echo 'very very very very very very very very very very very very long line' | base64
> dmVyeSB2ZXJ5IHZlcnkgdmVyeSB2ZXJ5IHZlcnkgdmVyeSB2ZXJ5IHZlcnkgdmVyeSB2ZXJ5IHZl
> cnkgbG9uZyBsaW5lCg==
> ```
> 
> 被折行了。
> 
> 可能作者发现`base64`命令来源于`/bin/base64`，实际则是`busybox`的软连接，只提供最最最基础的base64编解码功能，并不提供类似于来自于`coreutils`包里的`base64 -w 0`这样的参数截断换行。于是作者搞了个非常复杂的方式，就是不知道搞了哪个魔改版本的base64来取消默认换行行为。
> 
> 但是这个版本的`base64`编译又有点问题，在R2D运行就是经常会段错误。
> 
> 所以我的解决方案非常简单，就是直接用`tr`删掉换行符就完事了。
> 
> 另: R2D的`/usr/bin/base64`命令是来源于`coreutils`的，提供了`-w`参数，为了更加通用，不依赖`base64`命令的来源，所以还是采用了`tr`删掉换行符的方案

牛逼 可以了

**Comment by saintmob** [comment]
感谢 @abcfy2 ，这阵子困扰已久的问题解决了一半。

另一半是，同样也是跟本 issue 同时发生，原本我用着 ss 是支持 obfs: http 的，但现在只要启用 obfs （不指定 host）就必然导致 ss 无法启动。感觉跟版本升级了 obfs-local 有关？若各位同样遇到，非常期待能够解决。如有需要我会尽量协助测试。谢谢。

**Comment by abcfy2** [comment]
启动不了的如果有错误日志的话你可以在/etc/mixbox/var/log找找日志看看有没有错误信息，如果压根都没启动起来的话，可能连日志都没有，这时候你可以通过-x参数debug一下启动脚本，抓一下你的程序的启动命令，手工执行一下看看终端报什么错

**Comment by saintmob** [comment]
> 启动不了的如果有错误日志的话你可以在/etc/mixbox/var/log找找日志看看有没有错误信息，如果压根都没启动起来的话，可能连日志都没有，这时候你可以通过-x参数debug一下启动脚本，抓一下你的程序的启动命令，手工执行一下看看终端报什么错

一、有 obfs ，运行失败的情况（共 2 ）

1）以 xchacha20-ietf-poly1305 协议且 obfs: http ，运行失败：

> root@XiaoQiang:~# cat /etc/mixbox/var/log/ss-local.log
>  2020-04-18 16:20:48 INFO: plugin "/etc/mixbox/apps/shadowsocks/bin/obfs-local" enabled
>  2020-04-18 16:20:48 INFO: initializing ciphers... xchacha20-ietf-poly1305
>  2020-04-18 16:20:48 INFO: This system doesn't provide enough entropy to quickly generate high-quality random numbers.
> Installing the rng-utils/rng-tools, jitterentropy or haveged packages may help.
> On virtualized Linux environments, also consider using virtio-rng.
> The service will not start until enough entropy has been collected.
> 
>  2020-04-18 16:20:48 INFO: listening at 0.0.0.0:1082
>  2020-04-18 16:20:48 INFO: running from root user
> 
> simple-obfs 0.0.4
> 
>   maintained by Max Lv <max.c.lv@gmail.com>
> 
>   usage:
> 
>     obfs-local
> 
>        -s <server_host>           Host name or IP address of your remote server.
>        -p <server_port>           Port number of your remote server.
>        -l <local_port>            Port number of your local server.
>        --obfs <http|tls>          Enable obfuscating: HTTP or TLS (Experimental).
>        --obfs-host <host_name>    Hostname for obfuscating (Experimental).
> 
>        [-a <user>]                Run as another user.
>        [-f <pid_file>]            The file path to store pid.
>        [-t <timeout>]             Socket timeout in seconds.
>        [-c <config_file>]         The path to config file.
>        [-n <number>]              Max number of open files.
>        [-b <local_address>]       Local address to bind.
> 
> 
>        [--fast-open]              Enable TCP fast open.
>                                   with Linux kernel > 3.7.0.
>        [--mptcp]                  Enable Multipath TCP on MPTCP Kernel.
> 
>        [-v]                       Verbose mode.
>        [-h, --help]               Print this message.
> 
>  2020-04-18 16:20:48 ERROR: plugin service exit unexpectedly


2）以 aes-256-cfb 协议且 obfs: http ，运行失败：

> root@XiaoQiang:~# cat /etc/mixbox/var/log/ss-local.log
>  2020-04-18 16:31:49 INFO: plugin "/etc/mixbox/apps/shadowsocks/bin/obfs-local" enabled
>  2020-04-18 16:31:49 INFO: initializing ciphers... aes-256-cfb
>  2020-04-18 16:31:49 INFO: listening at 0.0.0.0:1082
>  2020-04-18 16:31:49 INFO: running from root user
> 
> simple-obfs 0.0.4
> 
>   maintained by Max Lv <max.c.lv@gmail.com>
> 
>   usage:
> 
>     obfs-local
> 
>        -s <server_host>           Host name or IP address of your remote server.
>        -p <server_port>           Port number of your remote server.
>        -l <local_port>            Port number of your local server.
>        --obfs <http|tls>          Enable obfuscating: HTTP or TLS (Experimental).
>        --obfs-host <host_name>    Hostname for obfuscating (Experimental).
> 
>        [-a <user>]                Run as another user.
>        [-f <pid_file>]            The file path to store pid.
>        [-t <timeout>]             Socket timeout in seconds.
>        [-c <config_file>]         The path to config file.
>        [-n <number>]              Max number of open files.
>        [-b <local_address>]       Local address to bind.
> 
> 
>        [--fast-open]              Enable TCP fast open.
>                                   with Linux kernel > 3.7.0.
>        [--mptcp]                  Enable Multipath TCP on MPTCP Kernel.
> 
>        [-v]                       Verbose mode.
>        [-h, --help]               Print this message.
> 
>  2020-04-18 16:31:49 ERROR: plugin service exit unexpectedly


二、无 obfs ，运行成功的情况（共 3 ）

1）以 xchacha20-ietf-poly1305 协议且无 obfs ，运行成功，但仍然有问题：

> root@XiaoQiang:~# cat /etc/mixbox/var/log/ss-local.log
>  2020-04-18 16:24:38 INFO: initializing ciphers... xchacha20-ietf-poly1305
>  2020-04-18 16:24:38 INFO: This system doesn't provide enough entropy to quickly generate high-quality random numbers.
> Installing the rng-utils/rng-tools, jitterentropy or haveged packages may help.
> On virtualized Linux environments, also consider using virtio-rng.
> The service will not start until enough entropy has been collected.
> 
>  2020-04-18 16:24:38 INFO: listening at 0.0.0.0:1082
>  2020-04-18 16:24:38 INFO: running from root user

2）以 chacha20-ietf-poly1305 协议且无 obfs ，运行成功：

> root@XiaoQiang:~# cat /etc/mixbox/var/log/ss-local.log
>  2020-04-18 16:29:54 INFO: initializing ciphers... chacha20-ietf-poly1305
>  2020-04-18 16:29:54 INFO: listening at 0.0.0.0:1082
>  2020-04-18 16:29:54 INFO: running from root user

3）以 aes-256-cfb 协议且无 obfs ，运行成功：

> root@XiaoQiang:~# cat /etc/mixbox/var/log/ss-local.log
>  2020-04-18 16:32:44 INFO: initializing ciphers... aes-256-cfb
>  2020-04-18 16:32:44 INFO: listening at 0.0.0.0:1082
>  2020-04-18 16:32:44 INFO: running from root user


----
所以是 obfs 环节的问题？
我也尝试过安装 rngd 或 haveged ，但不熟悉 busybox 所以不得其法。

盼指教，谢谢！
