### ISSUE TITLE
[Feture Request]备份建议增加config目录

### ISSUE THREAD

**Issue by abcfy2** [monlor/MIXBOX#129]
多么痛的觉悟，辛辛苦苦调教了半天的aria2配置，被升级覆盖了，一看备份傻眼了，没有config目录。

建议备份的时候将config目录一并备份

**Comment by monlor** [comment]
aria2确实没考虑自己修改配置的情况，之后会考虑这点

**Comment by abcfy2** [comment]
仓库好大，建议二进制文件考虑用git-lfs存储吧，github和coding应该都是支持的

**Comment by monlor** [comment]
现在仓库的容量我已经尽量减少了，程序有这么多，没办法。已经把一部分内容通过ci放到另一个仓库了。github提供的lfs空间特别少，不够用。
