### ISSUE TITLE
[Bug Report]R2D的dms控件无法启动？

### ISSUE THREAD

**Issue by fjhxh123** [monlor/MIXBOX#130]
**Bug 详情**

R2D的dms控件无法启动？

**你的操作**

********* DMS ***********
[dms是一款DLNA数字媒体服务器]
启动dms服务[1/0] [回车即1]：
请输入dms媒体目录[回车即/userdisk/data]：
请输入dms媒体服务器名称[回车即mixbox-dms]：
重启dms服务[1/0] [回车即1]：
【DMS】: 正在停止dms服务...
【DMS】: 正在启动dms服务...
Illegal instruction (core dumped)
【DMS】: 启动dms服务完成！

**屏幕截图**
![image](https://user-images.githubusercontent.com/59494264/78767910-c76fe380-79bd-11ea-96a1-3cb4f21c1bb2.png)

**日志信息**

无日志

**Comment by abcfy2** [comment]
段错误的问题应该跟这个一样： https://github.com/monlor/MIXBOX/issues/127#issuecomment-612424809

添加定时任务就可能会报段错误。

但是无法启动跟这个无关，你应该看看日志有无报错，日志应该是在`/etc/mixbox/var/log/`，找找你的服务看看什么错误

**Comment by monlor** [comment]
r2d无法启动就忽略吧，这个是用来做dlna的，主要给r3p开发的，除r3p外，其他设备都有dlna服务吧？
