### ISSUE TITLE
[Bug Report] vsftpd无法启动.

### ISSUE THREAD

**Issue by 48021129** [monlor/MIXBOX#135]
**Bug 详情**

vsftpd显示[运行端口号:21],实际上根本没有启动.
telnet 后,显示无法连接.
当前版本：[0.1.9.7]
设备型号：[R2D] 

**你的操作**

**屏幕截图**
![image](https://user-images.githubusercontent.com/10596138/79419727-f6074300-7fe9-11ea-95da-535efbb17088.png)

![image](https://user-images.githubusercontent.com/10596138/79419738-fc95ba80-7fe9-11ea-9ee8-8abc26ee7074.png)

**日志信息**
日志内容为空

```
```

**Comment by abcfy2** [comment]
R2D的ip默认是`192.168.31.1`，你在局域网也可以用`miwifi.com`这个域名连接

**Comment by 48021129** [comment]
> R2D的ip默认是`192.168.31.1`，你在局域网也可以用`miwifi.com`这个域名连接

我改过路由器的IP的.

**Comment by abcfy2** [comment]
那你应该检查下服务启动日志，以及ps看下进程列表确认下是否真的启动了，以及启动有没有错误

/etc/mixbox/var/log找找相关的日志看看

**Comment by 48021129** [comment]
> 那你应该检查下服务启动日志，以及ps看下进程列表确认下是否真的启动了，以及启动有没有错误
> 
> /etc/mixbox/var/log找找相关的日志看看。
> 
> 另外小米R2D自带就有samba，明明更好用为何还要再启动一个vsftpd？明明内存就比较紧张，就省着点用吧，不然温度会太高

感谢回答,日志看过,没有任何内容.进程也查不到vsftpd
我局域网中有一台服务器,使用Duplicati备份工具,而Duplicati不支持samba,我已经把小米的共享挂载到系统上了.直接可以使用了.

**Comment by monlor** [comment]
现在没有设备，无法测试vsftpd不能启动的原因，尝试使用别的工具代替吧

**Comment by 48021129** [comment]
> 现在没有设备，无法测试vsftpd不能启动的原因，尝试使用别的工具代替吧

好的.谢谢.
