### ISSUE TITLE
如何修改transmission的参数设置？

### ISSUE THREAD

**Issue by Loopodi** [monlor/MIXBOX#137]
默认状态下，路径/etc/mixbox/apps/transmission/config下的settings.json为tr的设置文件

修改文件参数保存后，tr并未生效。
用mixbox重启tr服务，又会变成默认状态下settings.json参数。

怎样才能用mixbox重启tr服务后，让我设置的settings.json文件自动生效？

**Comment by Loopodi** [comment]
已经解决问题，修改script目录下transmission.sh的脚本文件

**Comment by wangchenyan** [comment]
@Loopodi 请问有遇到 transmission 重启后，设置项自动恢复成默认的问题吗？比如限制上传速度
