### ISSUE TITLE
v2ray 启动代理为v2ray，测试配置文件 【ShadowSocks】: 配置文件测试失败！

### ISSUE THREAD

**Issue by iuimm** [monlor/MIXBOX#138]
请问黑名单模式和白名单模式是什么意思？
我可以像v2ray那样分开代理吗？
就是国内的视频网站，我们不走代理，国外的自动代理吗？

大佬 这是什么意思？为什么启动失败哦？配置文件测试失败是什么意思？

00. 返回主菜单
01. shadowsocks	[未运行] 
请输入你的选择：01
ShadowSocks 
[最好的翻墙工具，没有之一，还可以加速国内外游戏]
启动shadowsocks服务[1/0] [回车即1]：1
添加shadowsocks节点？[1/0] 0
修改shadowsocks配置(日本, gfwlist)？[1/0] 0
进入shadowsocks高级设置？[1/0] 0
【ShadowSocks】: 关闭ss主进程...
【ShadowSocks】: 删除nat-start触发...
【ShadowSocks】: 清除iptables规则...
【ShadowSocks】: 启动kcptun加速主进程(1)...
【ShadowSocks】: 创建节点配置文件...
【ShadowSocks】: 检测v2ray版本，本地版本：4.4，在线版本：4.4
【ShadowSocks】: 生成V2Ray配置文件...
【ShadowSocks】: 启动代理为v2ray，测试配置文件
【ShadowSocks】: 配置文件测试失败！
=========================
重新卸载之后有测试了一下
请选择shadowsocks节点：1
[1.黑名单模式 2.白名单模式 3.全局模式 4.回国模式]
请选择shadowsocks模式：3
进入shadowsocks高级设置？[1/0] 0
【ShadowSocks】: 关闭ss主进程...
【ShadowSocks】: 删除nat-start触发...
【ShadowSocks】: 清除iptables规则...
【ShadowSocks】: 创建节点配置文件...
【ShadowSocks】: 检测v2ray版本，本地版本：，在线版本：4.4
【ShadowSocks】: 版本不一致，正在更新...
【ShadowSocks】: 生成V2Ray配置文件...
【ShadowSocks】: 启动代理为v2ray，测试配置文件
Segmentation fault
【ShadowSocks】: 配置文件测试失败！
======================================
我选择白名单模式，却好像可以了
[1.黑名单模式 2.白名单模式 3.全局模式 4.回国模式]
请选择shadowsocks模式：2
进入shadowsocks高级设置？[1/0] 0
【ShadowSocks】: 关闭ss主进程...
【ShadowSocks】: 删除nat-start触发...
【ShadowSocks】: 清除iptables规则...
【ShadowSocks】: 创建节点配置文件...
【ShadowSocks】: 检测v2ray版本，本地版本：，在线版本：4.4
【ShadowSocks】: 版本不一致，正在更新...
【ShadowSocks】: 生成V2Ray配置文件...
【ShadowSocks】: 启动代理为v2ray，测试配置文件
【ShadowSocks】: 启动v2ray主进程(日本)...
【ShadowSocks】: 创建ipset规则...
【ShadowSocks】: 加载iptables的nat规则...
【ShadowSocks】: 添加国外白名单规则...
【ShadowSocks】: 加载ACL规则:[DESKTOP-EU9I68E]代理模式为:[不走代理]
【ShadowSocks】: 加载ACL规则:[MiAiSoundbox-LX04]代理模式为:[不走代理]
【ShadowSocks】: 加载ACL规则:[chuangmi-plug-m3_miio236712715]代理模式为:[不走代理]
【ShadowSocks】: 加载ACL规则:[OnePlus5]代理模式为:[不走代理]
【ShadowSocks】: 加载ACL规则:[其余主机]代理模式为:[科学上网]
【ShadowSocks】: 开启dns2socks进程...
【ShadowSocks】: 添加nat-start触发事件...
【ShadowSocks】: 启动shadowsocks服务完成，启动失败可查看日志或多次重试！

**Comment by monlor** [comment]
黑名单是只代理国内地址，白名单是不代理国外地址
