### ISSUE TITLE
Entware安装有404报错

### ISSUE THREAD

**Issue by 1987skywalker** [monlor/MIXBOX#14]
[一款开源且强大的包管理工具，许多功能都通过它来实现]
启动entware服务[1/0] [回车即0]：1
请输入entware安装路径[回车即/etc/.Entware]：
安装ONMP后，请勿安装工具箱插件HttpFile和KodExplorer
启动ONMP安装程序？[1/0] 1
【Entware】: 正在停止entware服务... 
【Entware】: 停止成功，请运行source /etc/profile使配置生效!
【Entware】: 若要重置【entware】服务，删除/etc/.Entware文件并启动即可
【Entware】: 正在启动entware服务... 
【Entware】: 初始化entware服务...
【Entware】: 启动依赖entware的所有插件...
【Entware】: entware服务启动完成
curl: (22) The requested URL returned error: 404 Not Found

小米路由器3G，请问是什么原因

**Comment by monlor** [comment]
onmp已修复
