### ISSUE TITLE
无法安装，下载失败

### ISSUE THREAD

**Issue by MonsieurCao** [monlor/MIXBOX#146]
想重新安装但是文件无法下载，非常需要望能尽快修复，拜托拜托！！！

![image](https://user-images.githubusercontent.com/64627618/80784354-559b4c00-8baf-11ea-92b0-ca88de297c2a.png)

**Comment by yantaocool** [comment]
我也是，有源代码我都不知道怎么安装，希望出个源码安装教程

**Comment by monlor** [comment]
已恢复
