### ISSUE TITLE
小米R3P下面的v2ray始终无法使用

### ISSUE THREAD

**Issue by Xavierwei** [monlor/MIXBOX#148]
**Bug 详情**
报错如下。重新安装重启也没有用,  尝试很多次. 麻烦解决一下谢谢. 

【ShadowSocks】: 关闭ss主进程...
【ShadowSocks】: 删除nat-start触发...
【ShadowSocks】: 清除iptables规则...
【ShadowSocks】: 创建节点配置文件...
【ShadowSocks】: 检测v2ray版本，本地版本：，在线版本：4.23.1
【ShadowSocks】: 版本不一致，正在更新...
【ShadowSocks】: 生成V2Ray配置文件...
【ShadowSocks】: 启动代理为v2ray，测试配置文件
Segmentation fault
【ShadowSocks】: 配置文件测试失败！

**你的操作**

**屏幕截图**

**日志信息**

```
```

**Comment by Xavierwei** [comment]
小米R2D同样问题，都是配置文件测试失败。都没法使用v2ray, 以前都正常使用

**Comment by monlor** [comment]
再次尝试一下，已更新v2ray二进制

**Comment by Xavierwei** [comment]
> 再次尝试一下，已更新v2ray二进制

已经可以正常使用, 多谢.
顺便请问一下为何R2D下面有游戏模式, R3P下则没有.

**Comment by Xavierwei** [comment]
> 
> 
> 再次尝试一下，已更新v2ray二进制

R3P测试下来是没问题，但是在R2D下面还是报错，尝试多次不行，麻烦参考下面

【ShadowSocks】: 关闭ss主进程...
【ShadowSocks】: 删除nat-start触发...
【ShadowSocks】: 清除iptables规则...
【ShadowSocks】: 创建节点配置文件...
【ShadowSocks】: 检测v2ray版本，本地版本：4.23.1，在线版本：4.23.1
【ShadowSocks】: 生成V2Ray配置文件...
【ShadowSocks】: 启动代理为v2ray，测试配置文件
【ShadowSocks】: 配置文件测试失败！
