### ISSUE TITLE
[Bug Report] 新版本无法下载

### ISSUE THREAD

**Issue by lslzl3000** [monlor/MIXBOX#151]
小米路由1代，5.4号版本更新后，无法更新插件，删除工具箱后，也无法再次安装工具箱

都是提示"文件下载失败！"，是我的问题还是脚本问题？

**Comment by supergenius** [comment]
附议，我在公司和家里都无法下载。

**Comment by Jestom** [comment]
大家都坏掉了

**Comment by Jestom** [comment]
现在已经可以了

**Comment by monlor** [comment]
重新安装或更换下载源：https://monlor.coding.net/p/mbfiles/d/mbfiles/git/lfs/master
