### ISSUE TITLE
[Bug Report]卸载了工具箱。重新安装了一遍, shadowsocks插件装不上了

### ISSUE THREAD

**Issue by Xavierwei** [monlor/MIXBOX#153]
**Bug 详情**
测试设备小米R2D, 多次尝试安装不上ss. 
     *****   MIXBOX 工具箱   *****     
***************************************
当前版本：[0.1.9.9]	最新版本：[0.1.9.9]
设备型号：[R2D]  	核心温度：[68°C]

请输入你的选择：23
确定要安装shadowsocks插件？[1/0] 1
【Tools】: 开始安装【shadowsocks】插件...
【Tools】: 下载插件安装文件...
【Tools】: 解压安装文件...
【Tools】: 文件解压失败！

**你的操作**

**屏幕截图**

**日志信息**

```
```

**Comment by jwangb7111** [comment]
R3D路由，之前0.1.9.8自动升级失败，且shadowsocks服务一直无法正常起来（生成V2Ray配置时出错）； 今天手动升级MIxbox到0.1.9.9，结果发现shadowsocks安装不上去了，求解

**Comment by monlor** [comment]
1. 重新安装或更换下载源：https://monlor.coding.net/p/mbfiles/d/mbfiles/git/lfs/master
2. v2ray无法使用是确认由于最近的一次更新导致的么？

**Comment by Xavierwei** [comment]
> * 重新安装或更换下载源：https://monlor.coding.net/p/mbfiles/d/mbfiles/git/lfs/master
> * v2ray无法使用是确认由于最近的一次更新导致的么？

前面试了一下全部重新安装。现在ss可以用了。但是v2ray还是不行。R2D下面是上一个版本更新后我记得就不能用了。参考下面刚刚尝试v2ray的结果

【ShadowSocks】: 关闭ss主进程...
【ShadowSocks】: 删除nat-start触发...
【ShadowSocks】: 清除iptables规则...
【ShadowSocks】: 创建节点配置文件...
【ShadowSocks】: 检测v2ray版本，本地版本：4.23.1，在线版本：4.23.1
【ShadowSocks】: 生成V2Ray配置文件...
【ShadowSocks】: 启动代理为v2ray，测试配置文件
【ShadowSocks】: 配置文件测试失败！

按任意键返回.

**Comment by jwangb7111** [comment]
![image](https://user-images.githubusercontent.com/34438897/81272317-e8405d00-907f-11ea-9075-8b5a3dd8fcb4.png)

我也一样的错误

**Comment by monlor** [comment]
已回滚v2ray配置

**Comment by jwangb7111** [comment]
还是显示 配置文件测试失败  SS没法启动

**Comment by Xavierwei** [comment]
> 已回滚v2ray配置

更新了插件 还是同样的报错。请看下面
【ShadowSocks】: 关闭ss主进程...
【ShadowSocks】: 删除nat-start触发...
【ShadowSocks】: 清除iptables规则...
【ShadowSocks】: 创建节点配置文件...
【ShadowSocks】: 检测v2ray版本，本地版本：4.23.1，在线版本：4.23.1
【ShadowSocks】: 生成V2Ray配置文件...
【ShadowSocks】: 启动代理为v2ray，测试配置文件
【ShadowSocks】: 配置文件测试失败！

按任意键返回.

**Comment by jwangb7111** [comment]
********* ShadowSocks ***********
[最好的翻墙工具，没有之一，还可以加速国内外游戏]
启动shadowsocks服务[1/0] [回车即1]：1
添加shadowsocks节点？[1/0] 0
修改shadowsocks配置(Google Cloud - HK 4, gfwlist)？[1/0] 0
进入shadowsocks高级设置？[1/0] 0
【ShadowSocks】: 关闭ss主进程...
【ShadowSocks】: 删除nat-start触发...
【ShadowSocks】: 清除iptables规则...
【ShadowSocks】: 创建节点配置文件...
【ShadowSocks】: 检测v2ray版本，本地版本：4.23.1，在线版本：4.23.1
【ShadowSocks】: 生成V2Ray配置文件...
【ShadowSocks】: 启动代理为v2ray，测试配置文件
【ShadowSocks】: 配置文件测试失败！

按任意键返回.
