### ISSUE TITLE
[Bug Report] 升级到Mixbox 0.1.9.9后 Shadowsocks插件无法安装

### ISSUE THREAD

**Issue by jwangb7111** [monlor/MIXBOX#154]
![image](https://user-images.githubusercontent.com/34438897/81267659-6816f900-9079-11ea-9485-ebfd486e8cc7.png)

路由器R3D，之前安装的是0.1.9.8，自动升级失败（手动也失败）只能重装到0.1.9.9，重装Shadowsocks插件时一直报错 详见附件图片

**Comment by monlor** [comment]
重新安装或更换下载源：https://monlor.coding.net/p/mbfiles/d/mbfiles/git/lfs/master
