### ISSUE TITLE
[Bug Report]V2RAY配置文件测试失败！

### ISSUE THREAD

**Issue by strike8424** [monlor/MIXBOX#155]
**Bug 详情**

使用新命令重新安装MIXBOX工具箱后，V2RAY配置文件没有回滚。启动的时候还是在线更新了4.23.1，最后测试失败。

**你的操作**

请输入你的选择：23
确定要安装shadowsocks插件？[1/0] 1
【Tools】: 开始安装【shadowsocks】插件...
【Tools】: 下载插件安装文件...
【Tools】: 解压安装文件...
【Tools】: 赋予可执行文件...
【Tools】: 处理器架构符合安装要求
【Tools】: 检查工具箱版本...
【Tools】: 工具箱版本[0.1.9.10]满足安装要求
【Tools】: 检查插件的额外安装脚本...
【Tools】: 初始化uci配置信息...
【Tools】: 添加插件到工具箱...
【Tools】: 插件安装完成！
-----------------------------------------
回滚v2ray配置
-----------------------------------------

按任意键返回.

【ShadowSocks】: 关闭ss主进程...
【ShadowSocks】: 删除nat-start触发...
【ShadowSocks】: 清除iptables规则...
【ShadowSocks】: 创建节点配置文件...
【ShadowSocks】: 检测v2ray版本，本地版本：，在线版本：4.23.1
【ShadowSocks】: 版本不一致，正在更新...
【ShadowSocks】: 生成V2Ray配置文件...
【ShadowSocks】: 启动代理为v2ray，测试配置文件
【ShadowSocks】: 配置文件测试失败！

按任意键返回.

**Comment by Jestom** [comment]
好像都是这样噗

**Comment by ts113csd** [comment]
遇到了相同的问题

**Comment by strike8424** [comment]
昨天晚上大神更新了测试失败也可以继续之后，虽然脚本继续跑了。但是到最后还是未运行状态。

如下
***************************************
     *****   MIXBOX 工具箱   *****     
***************************************
当前版本：[0.1.9.10]	最新版本：[0.1.9.10]
设备型号：[R1D]  	核心温度：[86°C]
***************************************
00. 返回主菜单
01. shadowsocks	[未运行] 

请输入你的选择：1
********* ShadowSocks ***********
[最好的翻墙工具，没有之一，还可以加速国内外游戏]
启动shadowsocks服务[1/0] [回车即0]：1
添加shadowsocks节点？[1/0] 0
修改shadowsocks配置(123, gfwlist)？[1/0] 0
进入shadowsocks高级设置？[1/0] 0
【ShadowSocks】: 关闭ss主进程...
【ShadowSocks】: 删除nat-start触发...
【ShadowSocks】: 清除iptables规则...
【ShadowSocks】: 创建节点配置文件...
【ShadowSocks】: 检测v2ray版本，本地版本：4.23.1，在线版本：4.23.1
【ShadowSocks】: 生成V2Ray配置文件...
【ShadowSocks】: 启动代理为v2ray，测试配置文件
【ShadowSocks】: 配置文件测试失败！
【ShadowSocks】: 启动v2ray主进程(123)...
【ShadowSocks】: 创建ipset规则...
【ShadowSocks】: 加载iptables的nat规则...
【ShadowSocks】: 添加国外黑名单规则...
【ShadowSocks】: 加载ACL规则:[全部主机]代理模式为:[科学上网]
【ShadowSocks】: 开启dns2socks进程...
【ShadowSocks】: 添加nat-start触发事件...
【ShadowSocks】: 启动shadowsocks服务完成，启动失败可查看日志或多次重试！

按任意键返回.

任意键后回到插件页面

***************************************
     *****   MIXBOX 工具箱   *****     
***************************************
当前版本：[0.1.9.10]	最新版本：[0.1.9.10]
设备型号：[R1D]  	核心温度：[86°C]
***************************************
00. 返回主菜单
01. shadowsocks	[未运行] 

请输入你的选择：

还是未运行状态。
家里的R1D R2D都是这样。

**Comment by vincent-edmodo** [comment]
同样的问题， V2ray无法使用了

**Comment by seagle0128** [comment]
同样的问题，v2ray 没法使用了，log 也没有错误信息。

**Comment by JandyLin1981** [comment]
我这里测试了, 包括把路由器复位重新安装,跟楼上的信息一样.显示

返回主菜单
shadowsocks [未运行]

测试路由器型号: R1D

**Comment by monlor** [comment]
v2ray程序更新了一下，现在应该不会测试配置文件失败了。执行rm -rf /etc/mixbox/apps/shadowsocks/bin/v2* 重启ss后可以更新v2ray程序

**Comment by strike8424** [comment]
感谢大神，问题已经解决。

**Comment by Xavierwei** [comment]
se

> v2ray程序更新了一下，现在应该不会测试配置文件失败了。执行rm -rf /etc/mixbox/apps/shadowsocks/bin/v2* 重启ss后可以更新v2ray程序

测试成功。多谢！

**Comment by jwangb7111** [comment]
嗯，终于能愉快的翻墙了，多谢大神
