### ISSUE TITLE
[Bug Report]R3P工具箱里没有任何插件可以安装

### ISSUE THREAD

**Issue by ZeroLLH** [monlor/MIXBOX#158]
**R3P工具箱里没有任何插件可以安装**
R3P工具箱里没有任何插件可以安装，不知道跟我使用中继器模式有没关系，路由器正常连接上网络的。

**你的操作**
我使用
sh -c "$(curl -kfsSl https://monlor.coding.net/p/mbfiles/d/mbfiles/git/lfs/master/install.sh)" && source /etc/profile &> /dev/null
安装了MIXBOX以后，在未安装插件里面看不到任何插件。
使用mixbox install shadowsocks命令也说无法安装。
我所有安装源都试过了，都不行。

**屏幕截图**
![image](https://user-images.githubusercontent.com/11505856/81480578-2ba3f280-925d-11ea-8b8c-bc93d0c4e115.png)
![image](https://user-images.githubusercontent.com/11505856/81480616-67d75300-925d-11ea-8278-84ee8280ecfc.png)

```
```

**Comment by monlor** [comment]
建议先多尝试几次，软件源有同时访问限制
