### ISSUE TITLE
AX3600适配情况

### ISSUE THREAD

**Issue by wzy461143268** [monlor/MIXBOX#168]
不知道大佬的原理是什么，目前恩山已经有人搞出来ax3600开启ssh的方法，不知道您的mixbox能不能在ax3600，armv8架构处理器使用呢？

**Comment by Gaojianli** [comment]
已经移植了，但是没有看到v2ray插件。。。arm的aarch64应该也能用吧

**Comment by wzy461143268** [comment]
> 已经移植了，但是没有看到v2ray插件。。。arm的aarch64应该也能用吧

那么其他插件可以使用吗，比如ssr，adbyby之类

**Comment by fredliang44** [comment]
> > 已经移植了，但是没有看到v2ray插件。。。arm的aarch64应该也能用吧
> 
> 那么其他插件可以使用吗，比如ssr，adbyby之类

SSR 是可以的

**Comment by fredliang44** [comment]
> 已经移植了，但是没有看到v2ray插件。。。arm的aarch64应该也能用吧

fixed

**Comment by wzy461143268** [comment]
> > 已经移植了，但是没有看到v2ray插件。。。arm的aarch64应该也能用吧
> 
> fixed, 等 pr merge 一下

目前固件升级这个漏洞活不下来的吧？一旦升级ssh是不是就关了？毕竟动态超频宽以及cpu超频有点眼馋。hhh

**Comment by Gaojianli** [comment]
@fredliang44 还是有些问题，比如可用空间不足的问题，不知道为啥ax3600 明明256的闪存可用只有一点点

**Comment by fredliang44** [comment]
> > > 已经移植了，但是没有看到v2ray插件。。。arm的aarch64应该也能用吧
> > 
> > 
> > fixed, 等 pr merge 一下
> 
> 目前固件升级这个漏洞活不下来的吧？一旦升级ssh是不是就关了？毕竟动态超频宽以及cpu超频有点眼馋。hhh

是有办法升级的，目前我是手动改了一下基础文件。后面要升级保留 ssh 可能需要 @monlor 有时间支持一下

**Comment by Gaojianli** [comment]
> > > > 已经移植了，但是没有看到v2ray插件。。。arm的aarch64应该也能用吧
> > > 
> > > 
> > > fixed, 等 pr merge 一下
> > 
> > 
> > 目前固件升级这个漏洞活不下来的吧？一旦升级ssh是不是就关了？毕竟动态超频宽以及cpu超频有点眼馋。hhh
> 
> 是有办法升级的，目前我是手动改了一下基础文件。后面要升级保留 ssh 可能需要 @monlor 有时间支持一下

怎么升级保留ssh啊？能给个提示吗？

**Comment by fredliang44** [comment]
> @fredliang44 还是有些问题，比如可用空间不足的问题，不知道为啥ax3600 明明256的闪存可用只有一点点

储存空间这个目前无解，`df -h` 看一下的话你可以看到能用的储存空间只有 20mb，剩下的都是重启丢失的 `/tmp`。也许可以考虑吧 binary 每次重启都下载到 `/tmp`执行？

**Comment by fredliang44** [comment]
> > > > > 已经移植了，但是没有看到v2ray插件。。。arm的aarch64应该也能用吧
> > > > 
> > > > 
> > > > fixed, 等 pr merge 一下
> > > 
> > > 
> > > 目前固件升级这个漏洞活不下来的吧？一旦升级ssh是不是就关了？毕竟动态超频宽以及cpu超频有点眼馋。hhh
> > 
> > 
> > 是有办法升级的，目前我是手动改了一下基础文件。后面要升级保留 ssh 可能需要 @monlor 有时间支持一下
> 
> 怎么升级保留ssh啊？能给个提示吗？

目前的策略可以保证在 10.0.20 (包含)之前的是 work 的，方法是 mixbox 作者把启动脚本放到 `/etc/firewall.user` 里面，路由器升级不会覆盖这个文件。但是在 10.0.20 之后系统不会默认执行`/etc/firewall.user` 了，我把MIXBOX 和开启 ssh 的启动脚本切换到 `/etc/udhcpc.user` (需要使用 dhcp 上网方式) 就可以升级保留 ssh & 开启 mixbox 了

**Comment by Gaojianli** [comment]
> > > > > > 已经移植了，但是没有看到v2ray插件。。。arm的aarch64应该也能用吧
> > > > > 
> > > > > 
> > > > > fixed, 等 pr merge 一下
> > > > 
> > > > 
> > > > 目前固件升级这个漏洞活不下来的吧？一旦升级ssh是不是就关了？毕竟动态超频宽以及cpu超频有点眼馋。hhh
> > > 
> > > 
> > > 是有办法升级的，目前我是手动改了一下基础文件。后面要升级保留 ssh 可能需要 @monlor 有时间支持一下
> > 
> > 
> > 怎么升级保留ssh啊？能给个提示吗？
> 
> 目前的策略可以保证在 10.0.20 (包含)之前的是 work 的，方法是 mixbox 作者把启动脚本放到 `/etc/firewall.user` 里面，路由器升级不会覆盖这个文件。但是在 10.0.20 之后系统不会默认执行`/etc/firewall.user` 了，我把 MIXBOX 和开启 **ssh 的启动脚本**切换到 `/etc/udhcpc.user` (需要使用 dhcp 上网方式) 就可以升级保留 ssh & 开启 mixbox 了
这个脚本可以升级保留，同时会自动执行？可以保留到10.0.50吗？

**Comment by fredliang44** [comment]
> @fredliang44 还是有些问题，比如可用空间不足的问题，不知道为啥ax3600 明明256的闪存可用只有一点点

有人提到可以试试 nfs，目前我通过 opkg 安装了相关 package，但是 mount nfs 的时候会卡死，暂时还没有定位到问题

**Comment by fredliang44** [comment]
> > > > > > > 已经移植了，但是没有看到v2ray插件。。。arm的aarch64应该也能用吧
> > > > > > 
> > > > > > 
> > > > > > fixed, 等 pr merge 一下
> > > > > 
> > > > > 
> > > > > 目前固件升级这个漏洞活不下来的吧？一旦升级ssh是不是就关了？毕竟动态超频宽以及cpu超频有点眼馋。hhh
> > > > 
> > > > 
> > > > 是有办法升级的，目前我是手动改了一下基础文件。后面要升级保留 ssh 可能需要 @monlor 有时间支持一下
> > > 
> > > 
> > > 怎么升级保留ssh啊？能给个提示吗？
> > 
> > 
> > 目前的策略可以保证在 10.0.20 (包含)之前的是 work 的，方法是 mixbox 作者把启动脚本放到 `/etc/firewall.user` 里面，路由器升级不会覆盖这个文件。但是在 10.0.20 之后系统不会默认执行`/etc/firewall.user` 了，我把 MIXBOX 和开启 **ssh 的启动脚本**切换到 `/etc/udhcpc.user` (需要使用 dhcp 上网方式) 就可以升级保留 ssh & 开启 mixbox 了
> 
> 这个脚本可以升级保留，同时会自动执行？可以保留到10.0.50吗？

可以的，我目前就是 10.0.50。如果有问题可以降级到 10.0.17，会重新执行 mixbox (但是 ssh 会丢失，重新破解 ssh 即可)，降级之后 mixbox 所有内容还是原样的。

**Comment by Gaojianli** [comment]
> > > > > > > > 已经移植了，但是没有看到v2ray插件。。。arm的aarch64应该也能用吧
> > > > > > > 
> > > > > > > 
> > > > > > > fixed, 等 pr merge 一下
> > > > > > 
> > > > > > 
> > > > > > 目前固件升级这个漏洞活不下来的吧？一旦升级ssh是不是就关了？毕竟动态超频宽以及cpu超频有点眼馋。hhh
> > > > > 
> > > > > 
> > > > > 是有办法升级的，目前我是手动改了一下基础文件。后面要升级保留 ssh 可能需要 @monlor 有时间支持一下
> > > > 
> > > > 
> > > > 怎么升级保留ssh啊？能给个提示吗？
> > > 
> > > 
> > > 目前的策略可以保证在 10.0.20 (包含)之前的是 work 的，方法是 mixbox 作者把启动脚本放到 `/etc/firewall.user` 里面，路由器升级不会覆盖这个文件。但是在 10.0.20 之后系统不会默认执行`/etc/firewall.user` 了，我把 MIXBOX 和开启 **ssh 的启动脚本**切换到 `/etc/udhcpc.user` (需要使用 dhcp 上网方式) 就可以升级保留 ssh & 开启 mixbox 了
> > 
> > 
> > 这个脚本可以升级保留，同时会自动执行？可以保留到10.0.50吗？
> 
> 可以的，我目前就是 10.0.50。如果有问题可以降级到 10.0.17，会重新执行 mixbox (但是 ssh 会丢失，重新破解 ssh 即可)，降级之后 mixbox 所有内容还是原样的。

不太行，这是我的脚本：
```
sed -i 's/channel=.*/channel=\"debug\"/g' /etc/init.d/dropbear
/etc/init.d/dropbear start
```
升级后ssh丢失了，能分享下你的脚本吗？
