### ISSUE TITLE
作者在吗？我他妈的今天被国宝请喝茶啦，你赶紧更新增加混淆协议！

### ISSUE THREAD

**Issue by vskllee** [monlor/MIXBOX#17]
作者在吗？我他妈的今天被国宝请喝茶啦，你赶紧更新增加混淆协议！
我问是不是撞库找见我号找见我的，他们说不是，说只要你上外网他们就能看见！难道https被破解了？联通的机房有手脚可以查到？还是SS没混淆

**Comment by monlor** [comment]
挺住，再等一会儿

**Comment by wangchuanyes** [comment]
翻墙无罪 怕什么
