### ISSUE TITLE
希望加入coremark跑分插件。

### ISSUE THREAD

**Issue by ZeaKyX** [monlor/MIXBOX#171]
对小米AX3600的性能比较感兴趣，希望能看到跑分成绩
Lean的openwrt自带源[cpumark](https://github.com/coolsnowwolf/lede/tree/master/package/lean/coremark)
原作者[coremark](https://github.com/eembc/coremark)
各种架构应该都全了吧

**Comment by abcfy2** [comment]
这种程序又不需要像服务那样长期后台运行，需要的话你自己交叉编译扔到路由器上自己运行就行了
