### ISSUE TITLE
有没有针对每个插件,能够写一些教程

### ISSUE THREAD

**Issue by suyisong** [monlor/MIXBOX#173]
比如ss,我之前在本机安装过,但是用box里面的设置好复杂.
白名单,黑名单,回国模式,也没有说明是啥意思.
最好能加一些教程

**Comment by suyisong** [comment]
白名单是指域名白名单,还是ip白名单?

**Comment by abcfy2** [comment]
别想了，这么多插件作者一个个写教程估计是没什么精力的，还是自己动手丰衣足食吧，自己看脚本去慢慢理解吧。

比如那几种模式看代码吧： https://github.com/monlor/MIXBOX/blob/master/apps/shadowsocks/config/mixbox.conf#L255

https://github.com/monlor/MIXBOX/blob/0caf17e92fb03e79f3bf5e58a58d7fe3e718d592/apps/shadowsocks/config/mixbox.conf#L255-L266

**Comment by abcfy2** [comment]
也就是黑名单模式对应`gfwlist`模式，走gfwlist自动代理，配置`customize_black.conf`手工加入代理列表，而`customize_white.conf`则从代理列表中去除某个地址。

如无特殊需求通常推荐“黑名单模式”，比较通用。

白名单模式恰好相反。国内恐怕没人会用这个模式吧。

全局模式就是全部走代理，不使用gfwlist和黑白名单

回国模式和白名单模式类似，但是会将`chnroute.txt`走代理，适合人在国外但是需要访问国内的CDN资源这种场景。

**Comment by XYZliang** [comment]
> 也就是黑名单模式对应`gfwlist`模式，走gfwlist自动代理，配置`customize_black.conf`手工加入代理列表，而`customize_white.conf`从代理列表中删除某个地址。
> 
> 如无特殊需求通常推荐“黑名单模式”，比较通用。
> 
> 白名单模式恰好相反。国内恐怕没人会用这个模式吧。
> 
> 整体模式就是全部走代理，不使用gfwlist和黑白名单
> 
> 回国模式和白名单模式类似，但替换`chnroute.txt`走代理，适合人在国外但是需要访问国内的CDN资源这种场景。

感谢感谢，我也懵了
