### ISSUE TITLE
更新v2ray-core

### ISSUE THREAD

**Issue by updater1234** [monlor/MIXBOX#174]
原因不多说了，最近V2ray爆出多个漏洞：
https://github.com/v2ray/v2ray-core/issues/2542
https://github.com/v2ray/discussion/issues/704

希望这边可以将v2ray-core更新到最新版。

**Comment by monlor** [comment]
新版在小米路由上兼容还不行，暂不考虑

**Comment by updater1234** [comment]
v2ray今天又发布了4.25.1，据说是提高了ARM平台的稳定性，不知真实效果如何？
