### ISSUE TITLE
AX1800 SS有错误

### ISSUE THREAD

**Issue by sleikang** [monlor/MIXBOX#175]
cp: can't stat '/etc/dnsmasq.d/*': No such file or directory

**Comment by sleikang** [comment]
【ShadowSocks】: 关闭ss主进程...
【ShadowSocks】: 删除nat-start触发...
【ShadowSocks】: 清除iptables规则...
cp: can't stat '/etc/dnsmasq.d/*': No such file or directory
【ShadowSocks】: 创建节点配置文件...
【ShadowSocks】: 检测v2ray版本，本地版本：，在线版本：4.23.1
【ShadowSocks】: 版本不一致，正在更新...
chmod: /etc/mixbox/apps/shadowsocks/bin/v2ray: No space left on device
chmod: /etc/mixbox/apps/shadowsocks/bin/v2ctl: No such file or directory
【ShadowSocks】: 生成V2Ray配置文件...
/etc/mixbox/apps/shadowsocks/scripts/general_v2ray_config.sh: local: line 25: not in a function
/etc/mixbox/apps/shadowsocks/scripts/general_v2ray_config.sh: local: line 26: not in a function
/etc/mixbox/apps/shadowsocks/scripts/general_v2ray_config.sh: local: line 27: not in a function
/etc/mixbox/apps/shadowsocks/scripts/general_v2ray_config.sh: local: line 28: not in a function
/etc/mixbox/apps/shadowsocks/scripts/general_v2ray_config.sh: local: line 29: not in a function
/etc/mixbox/apps/shadowsocks/scripts/general_v2ray_config.sh: local: line 78: not in a function
/etc/mixbox/apps/shadowsocks/scripts/general_v2ray_config.sh: local: line 150: not in a function
/etc/mixbox/apps/shadowsocks/scripts/general_v2ray_config.sh: line 152: can't create /etc/mixbox/apps/shadowsocks/config/v2ray.json: No space left on device
/etc/mixbox/apps/shadowsocks/scripts/general_v2ray_config.sh: line 176: can't create /etc/mixbox/apps/shadowsocks/config/v2ray.json: No space left on device
/etc/mixbox/apps/shadowsocks/scripts/general_v2ray_config.sh: line 191: can't create /etc/mixbox/apps/shadowsocks/config/v2ray.json: No space left on device
uci: I/O error
【ShadowSocks】: 启动代理为v2ray，测试配置文件
Segmentation fault
【ShadowSocks】: 配置文件测试失败！
【ShadowSocks】: 启动v2ray主进程(v2ray)...
/etc/mixbox/apps/shadowsocks/scripts/shadowsocks.sh: line 780: can't create /etc/mixbox/var/log/v2ray.log: No space left on device
【ShadowSocks】: 创建ipset规则...
【ShadowSocks】: 加载iptables的nat规则...
【ShadowSocks】: 添加国外黑名单规则...
【ShadowSocks】: 加载ACL规则:[全部主机]代理模式为:[科学上网]
【ShadowSocks】: 开启dns2socks进程...
/etc/mixbox/apps/shadowsocks/scripts/shadowsocks.sh: line 780: can't create /etc/mixbox/var/log/dns2socks.log: No space left on device
uci: I/O error
sh: write error: No space left on device
uci: I/O error
sh: write error: No space left on device
uci: I/O error
sh: write error: No space left on device
【ShadowSocks】: 添加nat-start触发事件...
uci: I/O error
cp: can't stat '/etc/dnsmasq.d/*': No such file or directory
【ShadowSocks】: 启动shadowsocks服务完成，启动失败可查看日志或多次重试！

**Comment by fredliang44** [comment]
@sleikang 
```bash
sh: write error: No space left on device
```

**Comment by monlor** [comment]
ax1800空间太小了 不建议使用v2ray
