### ISSUE TITLE
Dropbear 无法启动

### ISSUE THREAD

**Issue by jinglei207** [monlor/MIXBOX#179]
**Bug 详情**

Dropbear 无法启动，缺少证书什么的，小米路由器4A

**你的操作**
00. 返回主菜单
01. dropbear    [未运行]

请输入你的选择：1
********* DropBear ***********
[移植小米的SSH功能到工具箱]
[仅支持小米路由器！]
启动dropbear服务[1/0] [回车即1]：
请输入dropbear端口号[回车即1022]：
【慎重】是否启动时修改root用户密码[1/0]?
请输入dropbear外网访问配置[1/0][回车即0]：
【DropBear】: 正在停止dropbear服务...
【DropBear】: 删除nat-start触发...
【DropBear】: 正在启动dropbear服务...
【DropBear】: 服务启动端口号为：1022
【DropBear】: 检查dropbear配置文件中...
【DropBear】: 缺失证书文件无法启动！

**屏幕截图**

**日志信息**

```
我查了/etc/mixbox/var/log， 一个文件都没有。
```

**Comment by monlor** [comment]
已更新，10分钟后可以重试

**Comment by jinglei207** [comment]
> 
> 
> 已更新，10分钟后可以重试

`[移植小米的SSH功能到工具箱]
[仅支持小米路由器！]
启动dropbear服务[1/0] [回车即1]：1
请输入dropbear端口号[回车即22]：
【慎重】是否启动时修改root用户密码[1/0]? 
请输入dropbear外网访问配置[1/0][回车即1]：
【DropBear】: 正在停止dropbear服务... 
【DropBear】: 删除nat-start触发...
【DropBear】: 正在启动dropbear服务... 
【DropBear】: 服务启动端口号为：22
【DropBear】: 检查dropbear配置文件中...
cp: can't stat '/usr/sbin/dropbear': No such file or directory
cp: can't stat '/etc/dropbear/dropbear_rsa_host_key': No such file or directory
【DropBear】: 系统root用户密码将修改为：rj123456
Changing password for root
New password: 
Bad password: too weak
Retype password: 
Password for root changed by root
【DropBear】: 添加nat-start触发事件...
/userdisk/mixbox/apps/dropbear/scripts/dropbear.sh: line 78: /userdisk/mixbox/apps/dropbear/bin/dropbear: not found
【DropBear】: 启动dropbear服务完成！`

还是不行啊
