### ISSUE TITLE
小米路由器 Pro V2Ray无法启动

### ISSUE THREAD

**Issue by LeonWongInspiration** [monlor/MIXBOX#18]
您好，我在小米路由器 Pro上使用您的工具箱开启V2Ray失败，报错为unexpected '('，经查是由于小米路由器 Pro是mipsel的然而mixbox安装了mips的，请您修复这个问题，谢谢！

**Comment by monlor** [comment]
这个问题可能已经修复了，没修复再给我反馈吧
