### ISSUE TITLE
有谁知道怎么永久开启telnet吗？

### ISSUE THREAD

**Issue by jinglei207** [monlor/MIXBOX#180]
目前能用 https://github.com/acecilia/OpenWRTInvasion 开启telnet，但是每次重启都需要重新运行。
有没有什么办法能在重启之后telnet 直接开启？
我知道能用dropbear(虽然目前没成功)，但是如果能直接永久开启telnet的话就更好了。
谢谢大家的。小米路由器4A。

**Comment by monlor** [comment]
参考这个教程：https://www.monlor.com/posts/19407.html
开启telnet后再开启ssh，不升级的话重启不失效

**Comment by jinglei207** [comment]
> 
> 
> 参考这个教程：https://www.monlor.com/posts/19407.html
> 开启telnet后再开启ssh，不升级的话重启不失效
`root@XiaoQiang:~# sed -i ":x;N;s/if \[.*\; then\n.*return 0\n.*fi/#tb/;b x" /etc
/init.d/dropbear
sed: /etc/init.d/dropbear: No such file or directory
root@XiaoQiang:~# /etc/init.d/dropbear start
-ash: /etc/init.d/dropbear: not found
root@XiaoQiang:~# nvram set ssh_en=1; nvram commit
root@XiaoQiang:~#
`
是要安装dropbear吗？

**Comment by monlor** [comment]
你这个型号连dropbear都没有。。。

**Comment by jinglei207** [comment]
> 
> 
> 你这个型号连dropbear都没有。。。

所以我才想永久开启telnet啊，我试了一下webshell能用，但是只能粘贴一行。。。很垃圾啊。
有没有办法永久开启telnet？谢了大神。
