### ISSUE TITLE
更新工具箱报错

### ISSUE THREAD

**Issue by blackhumors** [monlor/MIXBOX#188]
![image](https://user-images.githubusercontent.com/20552372/85507049-3d323580-b624-11ea-98dc-6e95a5f8cbc7.png)
执行这句的时候无法解压
![image](https://user-images.githubusercontent.com/20552372/85507099-5509b980-b624-11ea-86bb-265856bbd1d2.png)

**Comment by monlor** [comment]
是不是下载源挂了？目前只有ghcdn能用
