### ISSUE TITLE
[Bug Report]源的失效导致插件无法工作

### ISSUE THREAD

**Issue by leo2430** [monlor/MIXBOX#193]
**Bug 详情**
最近发现经常性的安装源失效，而源的失效会导致正常运行的插件也失效，譬如shadowsocks

源失效可以导致无法获取新版本是正常的，不应该影响已安装版本的运行啊？

我知道更新源里输入新的源地址即可解决，但是此法并没有解决核心问题。就是源失效不应该影响现有版本的正常运行。
如果可以建立本地源的话，请告之方法，不胜感激

**Comment by monlor** [comment]
将这个[仓库](https://github.com/monlor/mbfiles)下载到你本地，搭建一个http服务器，配置下载源为你的服务器地址
