### ISSUE TITLE
[Bug Report]transmission启动失败

### ISSUE THREAD

**Issue by voodoozz** [monlor/MIXBOX#194]
**Bug 详情**

transmission可以安装，但是启动的时候失败
**屏幕截图**
启动transmission的时候报错: transmission-daemon-openssl安装失败！

[一款BT下载神器]
启动transmission服务[1/0] [回车即1]：请输入端口号[回车即9001]：
请输入下载路径[回车即/extdisks/sda1/transmission]：
启用认证用户[1/0][回车即1]：
请输入用户名[-1可不设置][回车即a]：
请输入密码[-1可不设置][回车即a]：
使用自定义高级UI[1/0][回车即1]：
重启transmission服务[1/0] [回车即1]：
【Transmission】: 正在停止transmission服务... 
【Transmission】: 删除nat-start触发...
【Transmission】: 正在启动transmission服务... 
Package oscam-emu version 2018-04-18-r11420_r769-1b has no valid architecture, ignoring.
Package ext-ui version 0.4-5a has no valid architecture, ignoring.
Package libdvbcsa version 1.1.0-1a has no valid architecture, ignoring.
Package oscam-emu version 2018-04-18-r11420_r769-1b has no valid architecture, ignoring.
Package ext-ui version 0.4-5a has no valid architecture, ignoring.
Package libdvbcsa version 1.1.0-1a has no valid architecture, ignoring.
Package oscam-emu version 2018-04-18-r11420_r769-1b has no valid architecture, ignoring.
Package ext-ui version 0.4-5a has no valid architecture, ignoring.
Package libdvbcsa version 1.1.0-1a has no valid architecture, ignoring.
Package oscam-emu version 2018-04-18-r11420_r769-1b has no valid architecture, ignoring.
Installing transmission-daemon-openssl (3.00-2) to root...
Downloading http://bin.entware.net/mipselsf-k3.4/transmission-daemon-openssl_3.00-2_mipsel-3.4.ipk
Installing libevent2 (2.1.11-2) to root...
Downloading http://bin.entware.net/mipselsf-k3.4/libevent2_2.1.11-2_mipsel-3.4.ipk
Collected errors:
 * opkg_install_pkg: Package size mismatch: libevent2 is 117656 bytes, expecting 117683 bytes
 * opkg_install_cmd: Cannot install package transmission-daemon-openssl.
【Transmission】: 程序transmission-daemon-openssl安装失败！
【Transmission】: 启动transmission服务完成！

按任意键返回.

**日志信息**

```
nohup: can't execute '/opt/bin/transmission-daemon': No such file or directory
```

**Comment by monlor** [comment]
`entware`的问题吧，建议联系`entware`官方

**Comment by wangchenyan** [comment]
@voodoozz 小米 R3D 启动 transmission 也有这个报错，不过不影响使用
