### ISSUE TITLE
[小米路由器 R3] VerySync 运行后无法访问

### ISSUE THREAD

**Issue by cychen95** [monlor/MIXBOX#2]
小米路由器 R3
系统版本 2.27.120

配置过程如下：
00. 返回主菜单

verysync	[运行端口号: 8886]

请输入你的选择: 05
********* VerySync ***********
[基于p2p的文件同步工具，局域网同步速度快]
启动verysync服务[1/0] [回车即1]：1
请输入verysync端口号[回车即8886]：
请输入verysync外网访问配置[1/0][回车即0]：0
【VerySync】: 正在停止verysync服务... 
【VerySync】: 删除nat-start触发...
【VerySync】: 卸载插件后可删除/etc/mixbox/apps/verysync/config文件夹
【VerySync】: 正在启动verysync服务... 
【VerySync】: 启动verysync服务完成！
【VerySync】: 请在浏览器中访问[http://192.168.31.1:8886]

按任意键返回.

返回后浏览器访问 http://192.168.31.1:8886 无法连接。如下图：

![图1](http://owncloud-c.oss-cn-shanghai.aliyuncs.com/19-1-7/QQ%E6%B5%8F%E8%A7%88%E5%99%A8%E6%88%AA%E5%9B%BE20190116220534.jpg)

**Comment by monlor** [comment]
贴一下日志

**Comment by cychen95** [comment]
mixbox 版本：[0.0.6]

`root@XiaoQiang:/etc/mixbox/var/log# cat verysync.log
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x857520, 0x16)
        /usr/local/go/src/runtime/panic.go:608 +0x60
runtime.sysMap(0x2000000, 0x800000, 0x10a01f8)
        /usr/local/go/src/runtime/mem_linux.go:156 +0xf0
runtime.(*linearAlloc).alloc(0x1091024, 0x800000, 0x400000, 0x10a01f8, 0x11c01)
        /usr/local/go/src/runtime/malloc.go:1230 +0xd0
runtime.(*mheap).sysAlloc(0x1090560, 0x800000, 0x108b2e0, 0x38f60)
        /usr/local/go/src/runtime/malloc.go:525 +0x78
runtime.(*mheap).grow(0x1090560, 0x400, 0x0)
        /usr/local/go/src/runtime/mheap.go:920 +0x4c
runtime.(*mheap).allocSpanLocked(0x1090560, 0x400, 0x10a0208, 0x3f30957e)
        /usr/local/go/src/runtime/mheap.go:848 +0x3ac
runtime.(*mheap).alloc_m(0x1090560, 0x400, 0xffff0101, 0x76f04)
        /usr/local/go/src/runtime/mheap.go:692 +0x14c
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:759 +0x5c
runtime.(*mheap).alloc(0x1090560, 0x400, 0x2b010101, 0xc43c66a1)
        /usr/local/go/src/runtime/mheap.go:758 +0x90
runtime.largeAlloc(0x800000, 0x70101, 0x2b97c000)
        /usr/local/go/src/runtime/malloc.go:1019 +0xa0
runtime.mallocgc.func1()
        /usr/local/go/src/runtime/malloc.go:914 +0x58
runtime.systemstack(0x795e8)
        /usr/local/go/src/runtime/asm_mipsx.s:207 +0x9c
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1229

goroutine 1 [running, locked to thread]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_mipsx.s:159 +0x8 fp=0x1478e1c sp=0x1478e18 pc=0x796c4
runtime.mallocgc(0x800000, 0x78efc0, 0xf00ee301, 0x153c000)
        /usr/local/go/src/runtime/malloc.go:913 +0x9a0 fp=0x1478e70 sp=0x1478e1c pc=0x1c924
runtime.makeslice(0x78efc0, 0x800000, 0x800000, 0x151a348, 0x5ed27414, 0x7200fa71)
        /usr/local/go/src/runtime/slice.go:70 +0xa4 fp=0x1478e84 sp=0x1478e70 pc=0x60154
verysync.com/verysync/lib/protocol.init.5()
        /Users/xujintian/go/src/verysync.com/verysync/lib/protocol/protocol.go:49 +0x6c fp=0x1478ed8 sp=0x1478e84 pc=0x43c338
verysync.com/verysync/lib/protocol.init()
        <autogenerated>:1 +0x1b44 fp=0x1478f50 sp=0x1478ed8 pc=0x4457fc
verysync.com/verysync/lib/config.init()
        <autogenerated>:1 +0xf8 fp=0x1478f80 sp=0x1478f50 pc=0x518d8c
main.init()
        <autogenerated>:1 +0x140 fp=0x1478fcc sp=0x1478f80 pc=0x7017c0
runtime.main()
        /usr/local/go/src/runtime/proc.go:189 +0x1f8 fp=0x1478fec sp=0x1478fcc pc=0x458e4
runtime.goexit()
        /usr/local/go/src/runtime/asm_mipsx.s:660 +0x4 fp=0x1478fec sp=0x1478fec pc=0x7ba6c

goroutine 6 [chan receive]:
verysync.com/verysync/vendor/verysync.com/notify.(*nonrecursiveTree).dispatch(0x1422300, 0x1422280)
        /Users/xujintian/go/src/verysync.com/verysync/vendor/verysync.com/notify/tree_nonrecursive.go:36 +0xc0
created by verysync.com/verysync/vendor/verysync.com/notify.newNonrecursiveTree
        /Users/xujintian/go/src/verysync.com/verysync/vendor/verysync.com/notify/tree_nonrecursive.go:29 +0xec

goroutine 7 [chan receive]:
verysync.com/verysync/vendor/verysync.com/notify.(*nonrecursiveTree).internal(0x1422300, 0x14222c0)
        /Users/xujintian/go/src/verysync.com/verysync/vendor/verysync.com/notify/tree_nonrecursive.go:81 +0x64
created by verysync.com/verysync/vendor/verysync.com/notify.newNonrecursiveTree
        /Users/xujintian/go/src/verysync.com/verysync/vendor/verysync.com/notify/tree_nonrecursive.go:30 +0x118

goroutine 8 [chan receive]:
verysync.com/verysync/lib/protocol.(*bufferPool).drain(0x14681e0)
        /Users/xujintian/go/src/verysync.com/verysync/lib/protocol/bufferpool.go:36 +0xc4
created by verysync.com/verysync/lib/protocol.newBufferPool
        /Users/xujintian/go/src/verysync.com/verysync/lib/protocol/bufferpool.go:28 +0x90

goroutine 9 [chan receive]:
verysync.com/verysync/lib/protocol.(*bufferPool).drain(0x1468210)
        /Users/xujintian/go/src/verysync.com/verysync/lib/protocol/bufferpool.go:36 +0xc4
created by verysync.com/verysync/lib/protocol.newBufferPool
        /Users/xujintian/go/src/verysync.com/verysync/lib/protocol/bufferpool.go:28 +0x90`

**Comment by monlor** [comment]
内存不够用了，没什么办法，小米路由器3貌似不支持虚拟内存

**Comment by monlor** [comment]
哦，可能不是，等我更新这个问题
