### ISSUE TITLE
小米路由器3G 重启后报错然后卸载重装也打不开mixbox了

### ISSUE THREAD

**Issue by 1987skywalker** [monlor/MIXBOX#20]
小米路由器3G的闪存好像是在/extdisks/sda1,因为之前安装设置在/userdisk/data和/etc都只能装2个插件.设置在/extdisks/sda1后安装多个使用正常,然后今天重启后却发现插件功能没了,ssh上去后报错:
-ash: source: line 16: can't open '/extdisks/sda1/mixbox/config/profile'
尝试重装无法启动mixbox:
sh -c "$(curl -kfsSl https://dev.tencent.com/u/monlor/p/MIXBOX
/git/raw/master/install.sh)" && source /etc/profile &> /dev/null

***********************************************
**                                           **
**            Welcome to MIXBOX !            **
**                                           **
***********************************************

【Tools】: 请按任意键安装工具箱(Ctrl + C 退出).

请在以下路径中选择一个合适的工具箱安装位置和一个用户文件目录：
小米路由器硬盘版推荐 工具箱安装位置：/etc，用户目录：/userdisk/data
小米路由器普通版推荐 工具箱安装位置：/etc，用户目录：/extdisks/sda*
如果未插入u盘，用户目录可与工具箱安装位置相同！
1./
2./dev
3./tmp
4./
5./tmp
6./extdisks
7./data
8./userdisk
9./userdisk/data
10./etc
请输入你的工具箱安装路径[可手动输入路径]：/etc
请输入你的用户文件目录[可手动输入路径]：/etc
工具箱已安装，清除并继续？[1/0] 1
【Tools】: 下载工具箱文件...
【Tools】: 解压工具箱文件
mixbox/
mixbox/bin/
mixbox/config/
mixbox/scripts/
mixbox/scripts/appmanage.sh
mixbox/scripts/uninstall.sh
mixbox/scripts/init.sh
mixbox/scripts/userscript.sh
mixbox/scripts/update.sh
mixbox/scripts/monitor.sh
mixbox/config/mixbox.uci
mixbox/config/profile
mixbox/bin/start-stop-daemon
mixbox/bin/versioncmp
mixbox/bin/mbdb
mixbox/bin/mixbox
mixbox/bin/applist
mixbox/bin/cru
mixbox/bin/base
【Tools】: 初始化工具箱配置信息...
【Tools】: 执行工具箱初始化脚本...
【Tools】: 工具箱初始化脚本启动...
【Tools】: 检查环境变量配置
【Tools】: 检查定时任务配置
【Tools】: 检查工具箱开机启动配置
【Tools】: 执行工具箱监控脚本
【Tools】: 防火墙重启插件检查
【Tools】: 运行用户自定义脚本
【Tools】: 工具箱安装完成!
【Tools】: 运行mixbox命令即可配置工具箱
root@XiaoQiang:~# mixbox
-ash: mixbox: not found
卸载重装还是这样.请问应该怎么解决呀?

**Comment by lonelygo** [comment]
Mini，也遇到同样的问题，装/ect下面，报空间不足，df -h看只有/extdisks 还有60M空间，安装后正常。
重启后，/extdisks 下面空了，是不是这个闪存空间是掉电就擦除的？

**Comment by 1987skywalker** [comment]
发现-ash: source: line 16: can't open '/extdisks/sda1/mixbox/config/profile' 报错导致卸载和重装都无效，在另一台小米路由器mini上用移动硬盘(/extdisks/sda1/)装了mixbox,放回这个小米路由器3G上才卸载重装成功。麻烦作者看下什么原因，不然只有一台可能出现这情况后没法解决了……

**Comment by monlor** [comment]
你们的/extdisks下面没有u盘或硬盘？不会只有60M空间吧

**Comment by Xie-Dong** [comment]
我的路由器是mini，以上重启失效的问题，我是把工具箱放在/extdisks/sda1下，把用户文件目录放到了/ect下，重启就不会失效了
