### ISSUE TITLE
【ShadowSocks】: 配置文件测试失败！

### ISSUE THREAD

**Issue by curryhendry** [monlor/MIXBOX#202]
一直无法配置失败，重新装也不行，辛苦哪位大神给看看。
<img width="568" alt="FB82948B-1B1E-445A-98F7-0C45969C653E" src="https://user-images.githubusercontent.com/61240122/88454767-4e30c980-cea4-11ea-948c-dfede1a42297.png">

ShadowSocks】: 检测v2ray版本，本地版本：，在线版本：4.23.1
【ShadowSocks】: 版本不一致，正在更新...
chmod: /tmp/mbtmp/v2ray: No such file or directory
测试v2ray程序失败！跳过更新...
【ShadowSocks】: 生成V2Ray配置文件...
【ShadowSocks】: 启动代理为v2ray，测试配置文件
/userdisk/data/mixbox/apps/shadowsocks/scripts/shadowsocks.sh: line 1: /userdisk/data/mixbox/apps/shadowsocks/bin/v2ray: not found
【ShadowSocks】: 配置文件测试失败！

**Comment by zjslqshqz** [comment]
你的 v2ray 都更新失败了，建议你更新一下 mixbox 在重新配置试试。或者更新一下 ShadowSocks app
正常情况下，在检测 v2ray 版本都时候，本地版本，应该和在线版本是一致的。

**Comment by curryhendry** [comment]
> 你的 v2ray 都更新失败了，建议你更新一下 mixbox 在重新配置试试。或者更新一下 ShadowSocks app
> 正常情况下，在检测 v2ray 版本都时候，本地版本，应该和在线版本是一致的。

是的，我后来重置了路由重新来过以后好了。感谢回复。
