### ISSUE TITLE
不支持PPTPD了吗？

### ISSUE THREAD

**Issue by adyhwang** [monlor/MIXBOX#214]
![image](https://user-images.githubusercontent.com/36879543/92321333-b229de80-f05b-11ea-98d2-157323fff61c.png)

没有找到PPTPD选项，用mixbox install PPTPD 安装，显示下载失败。

**Comment by monlor** [comment]
r3600的pptpd可以尝试使用[armv7](https://github.com/monlor/mbfiles/blob/master/appstore/pptpd_linux_arm.tar.gz)的版本，暂时没有编译armv8的版本，如果可以用的话，欢迎再次反馈

**Comment by adyhwang** [comment]
> r3600的pptpd可以尝试使用[armv7](https://github.com/monlor/mbfiles/blob/master/appstore/pptpd_linux_arm.tar.gz)的版本，暂时没有编译armv8的版本，如果可以用的话，欢迎再次反馈

启动Entware时，显示不支持设备，暂时无解了。
