### ISSUE TITLE
/etc/mixbox/scripts/monitor.sh 的效率问题

### ISSUE THREAD

**Issue by Dango233** [monlor/MIXBOX#217]
Crontab有一个任务是每三分钟运行一次monitor.sh，发现该任务会瞬间占用大量CPU, 产生minor_pagefault及新建大量Process，在路由高负载的时候造成卡顿或其他高实时性进程的错误

![image](https://user-images.githubusercontent.com/15649295/92403765-bf7ec000-f164-11ea-9ff7-70345ab4e5dd.png)

逐行运行脚本发现和applist update，及当前运行进程的status有关，可能需要优化

我目前的方案是手动修改crontab和monitor.sh，降低自检频率，绕过applist update逻辑，可以减少卡顿情况

**Comment by monlor** [comment]
可以考虑降低自检频率，10m一次；状态检查和applist更新暂时还没办法去掉。
