### ISSUE TITLE
shadowsocks 插件无法上网

### ISSUE THREAD

**Issue by huanglins** [monlor/MIXBOX#23]
通过电脑客户端配置ss 可以正常上网，路由器上启用插件后无法上网，且退出 mixbox 管理程序后，插件会自己停掉。

**Comment by aishlai** [comment]
我也是同样的问题，所以只能卸载了

**Comment by huanglins** [comment]
不知道是否是部分硬件的问题，我和我同事一模一样的配置，他的 R1D 可以使用，但是我的 R3D 无法使用。

**Comment by monlor** [comment]
先看看日志吧，/etc/mixbox/var/log

**Comment by aishlai** [comment]
我安装mt就是可以用的，现在用的还挺好
