### ISSUE TITLE
白名单导入方法的建议

### ISSUE THREAD

**Issue by RivenNero** [monlor/MIXBOX#27]
机型: R3P  #(小米路由器Pro)

是这样呢:

![image](https://user-images.githubusercontent.com/35187885/54873594-19c27e80-4e14-11e9-9a66-04f1a23ec066.png)

还是这样呢?

![image](https://user-images.githubusercontent.com/35187885/54873602-41194b80-4e14-11e9-90a2-10badedebc64.png)

如果我只输入pac或者白名单文件的url地址, 会导致路由器的web界面显示无法连接外网, 但是实际上是可以上外网的, 但是这样会影响到dhcp分配, 我的小米6就因此一直显示正在获取ip, 但是如果是直接写ip的话又要刷屏好一会儿, 作者可以添加一个导入文件的功能吗?

**Comment by monlor** [comment]
前者，不过也可以是域名

**Comment by monlor** [comment]
插件目录我有介绍，可以找找custom文件，来修改自定义规则

**Comment by RivenNero** [comment]
请问是这两个吗

![image](https://user-images.githubusercontent.com/35187885/54873674-8f2f4e80-4e16-11e9-8a6b-97e735b8e280.png)

**Comment by RivenNero** [comment]
OK 看来是这个了
