### ISSUE TITLE
whitelist: not found

### ISSUE THREAD

**Issue by RivenNero** [monlor/MIXBOX#28]
机型: R3P (小米路由器Pro)

已开启插件: 

![image](https://user-images.githubusercontent.com/35187885/54873715-ae7aab80-4e17-11e9-94e3-9d023f00775d.png)

如图, 启用白名单模式的时候会出现如下错误

![image](https://user-images.githubusercontent.com/35187885/54873709-84c18480-4e17-11e9-869c-f8bd705b8892.png)

**Comment by monlor** [comment]
重装一下吧，具体原因是uci里面有问题

**Comment by RivenNero** [comment]
emmmm 关键是我已经重装过2遍了 但是就是会报这个错 我的机型是R3P

**Comment by monlor** [comment]
这个是工具箱缺陷，等待改进

**Comment by RivenNero** [comment]
> 这个是工具箱缺陷，等待改进

好的

**Comment by monlor** [comment]
尝试最新版本看问题是否还存在呢
