### ISSUE TITLE
R1CM路由器Shadowsocks安装报错

### ISSUE THREAD

**Issue by MQL9011** [monlor/MIXBOX#29]
安装时候报了这个错,然后SS订阅也一直失败...

<img width="727" alt="6D86AB99-9429-4C84-A97F-410A4D478415" src="https://user-images.githubusercontent.com/11871158/54879182-e8c46700-4e70-11e9-829f-5bf35eccf2e4.png">

**Comment by dacklee** [comment]
安装目录选“8”
但有个问题，重启路由器后必须重新安装

**Comment by MQL9011** [comment]
我是用的小米路由青春版, 之前用Monlor是都是装在外置U盘内的. 不知道这个是不是也能装在外置U盘内.

**Comment by monlor** [comment]
可以安装在u盘

**Comment by MQL9011** [comment]
@monlor   我在安装 MixBox时, 路径选择中没有发现有 U盘的路径, 希望能直接增加一个选项,类似Monlor安装时, 直接选择安装在外置存储中.
