### ISSUE TITLE
gfwlist怎么样才能自定义呢？

### ISSUE THREAD

**Issue by ZhuojingXie** [monlor/MIXBOX#3]
我的最终目的是回国模式。但是发现默认的回国模式并不好用。好像国内的网站都会自定义走了ss，挺费流量的。所以我更希望用的是黑名单模式。但是黑名单模式自定义gfwlist，不太符合我的需求。请问要怎么解决 呢？

**Comment by Allen0618** [comment]
我这边是黑名单模式就连不了国外网站……

**Comment by RivenNero** [comment]
> 我这边是黑名单模式就连不了国外网站……

我也是一样的, 现在只能用白名单模式

**Comment by abcfy2** [comment]
我也发现gfwlist模式时灵时不灵，改过几次配置之后gfwlist好像就不生效了，怀疑是脚本的BUG
