### ISSUE TITLE
aria2小米路由3，新建任务的时候，就 断开连接

### ISSUE THREAD

**Issue by fishho** [monlor/MIXBOX#34]
点击新建，输入网址，确认，就跳成未连接。
此时再查看后台，aria2服务已经停止运行。

**Comment by fishho** [comment]
查看aria2.log无记录

**Comment by monlor** [comment]
小米路由3的aria2，已无力兼容，使用monlor-tools里的aria2吧

**Comment by monlor** [comment]
小米路由3的aria2，已无力兼容，使用monlor-tools里的aria2吧
