### ISSUE TITLE
小米路由器3G明明128M的闪存，为何装enware就空间不够，应该装哪里？

### ISSUE THREAD

**Issue by 1987skywalker** [monlor/MIXBOX#37]
root@XiaoQiang:~# df -h
Filesystem                Size      Used Available Use% Mounted on
rootfs                   18.8M     18.8M         0 100% /
none                    122.8M         0    122.8M   0% /dev
tmpfs                   123.6M      5.2M    118.4M   4% /tmp
/dev/mtdblock13          18.8M     18.8M         0 100% /
tmpfs                   123.6M      5.2M    118.4M   4% /tmp
tmpfs                   123.6M      5.2M    118.4M   4% /extdisks
ubi1_0                   43.5M     41.6M         0 100% /data
ubi1_0                   43.5M     41.6M         0 100% /userdisk
/dev/mtdblock13          18.8M     18.8M         0 100% /userdisk/data
ubi1_0                   43.5M     41.6M         0 100% /etc

安装尝试了的/etc、userdisk，安装enware一半都会报空间不足。小米路由器3G的128m闪存是哪个盘呢？根据https://openwrt.io/docs/miwifi/    的测试，dev和tmp重启后好像失效了，请问有什么办法转移点空间去安装目录吗？

**Comment by itfsw** [comment]
我是安装在移动硬盘上的，但是有一点注意是移动硬盘必须格式化成ext4格式
