### ISSUE TITLE
aria2点击new没有反应

### ISSUE THREAD

**Issue by nonotde** [monlor/MIXBOX#4]
小米路由r3p，安装好后可以进入界面，但是点击任何按钮都没有反应

![image](https://user-images.githubusercontent.com/44421711/51396381-f4966300-1b79-11e9-80ce-79dee60f8937.png)

![image](https://user-images.githubusercontent.com/44421711/51396423-05df6f80-1b7a-11e9-8f28-2d8757d32887.png)

**Comment by dhso** [comment]
控制台报错了，这个UI有问题。

**Comment by nonotde** [comment]
> 控制台报错了，这个UI有问题。

那怎么解决呢？

**Comment by monlor** [comment]
可以用aria2c.com

**Comment by dhso** [comment]
> > 控制台报错了，这个UI有问题。
> 
> 那怎么解决呢？

你去chrome store 安装这个插件就行。
https://chrome.google.com/webstore/detail/aria2-for-chrome/mpkodccbngfoacfalldjimigbofkhgjn

**Comment by wuye2764** [comment]
重新下载一个ariaNG上传到/etc/mixbox/apps/aria2/web/AriaNG就解决了

**Comment by nonotde** [comment]
> 重新下载一个ariaNG上传到/etc/mixbox/apps/aria2/web/AriaNG就解决了

多谢！！真 的好用
