### ISSUE TITLE
抱歉问一下应该怎么用

### ISSUE THREAD

**Issue by 18121259693** [monlor/mixbox#4]
如题我是小白
没注意到开发进度是未完成
我就把git clone下来，放到小米路由器R2D里
然后就执行了install
现在遇到2个棘手的问题
1 如果我要继续用，下一步该怎么用，即找不到web端端口，也找不到命令？
2 如果我不用了，应该如何正确卸载？

若能回答 十万分感谢！

**Comment by monlor** [comment]
cd到安装路径的scripts目录下，执行`./uninstall.sh`
