### ISSUE TITLE
路由器挂载外接硬盘时，程序启动快于硬盘挂载导致问题

### ISSUE THREAD

**Issue by itfsw** [monlor/MIXBOX#40]
现在使用过程中在外接硬盘时会存在一个问题，就是我们硬盘挂载需要一定时间，导致某些依赖硬盘启动的apps启动后出现一些问题。
比如verysync -home 读取不到，kodexplore检查是否已经下载这些都会偶发性出问题。
建议作者开机启动apps进行延迟一段时间（实测大概1分钟左右），谢谢。

**Comment by monlor** [comment]
欢迎提交pull requests😆

**Comment by monlor** [comment]
#35
