### ISSUE TITLE
安装entware提示创建目录失败

### ISSUE THREAD

**Issue by gm-fire** [monlor/MIXBOX#43]
********* Entware ***********
[一款开源且强大的包管理工具，许多功能都通过它来实现]
启动entware服务[1/0] [回车即0]：1
请输入entware安装路径[回车即/userdisk/data/.Entware]：
安装ONMP后，请勿安装工具箱插件HttpFile和KodExplorer
启动ONMP安装程序？[1/0] 1
【Entware】: 正在停止entware服务... 
【Entware】: 停止成功，请运行source /etc/profile使配置生效!
【Entware】: 若要重置【entware】服务，删除/userdisk/data/.Entware文件并启动即可
【Entware】: 正在启动entware服务... 
【Entware】: 初始化entware服务...
【Entware】: 检测到第一次运行entware服务，正在安装...
【Tools】: 创建目录失败，检查你的路径是否正确！
【Entware】: 正在停止entware服务... 
【Entware】: 停止成功，请运行source /etc/profile使配置生效!
【Entware】: 若要重置【entware】服务，删除/userdisk/data/.Entware文件并启动即可

**Comment by monlor** [comment]
检查设置的路径是否正确，是否为硬盘版路由器

**Comment by txxxtxx** [comment]
我的也是同样的问题，路由器是ax3600的，好像这个目录没有创建文件夹的权限/userdisk/data/
