### ISSUE TITLE
小米路由器3G接USB硬盘应该选那个版本?

### ISSUE THREAD

**Issue by gm-fire** [monlor/MIXBOX#44]
小米路由器硬盘版推荐 工具箱安装位置：/etc，用户目录：/userdisk/data
小米路由器普通版推荐 工具箱安装位置：/etc，用户目录：/extdisks/sda*

请问是选硬盘版还是普通版呢?普通版的用户目录是输入/extdisks/sda* 还是/extdisks/sda0 ?

**Comment by monlor** [comment]
当然是普通版，*代表任意的字符，你可以根据列出的选项选择

**Comment by gm-fire** [comment]
那昨晚装错了,晚上回去删除重装
