### ISSUE TITLE
onmp 安装失败

### ISSUE THREAD

**Issue by gm-fire** [monlor/MIXBOX#45]
Segmentation fault
Segmentation fault
wget 正在安装...
Segmentation fault
Segmentation fault
unzip 正在安装...
Segmentation fault
Segmentation fault
grep 正在安装...
Segmentation fault
Segmentation fault
sed 正在安装...
Segmentation fault
Segmentation fault
tar 正在安装...
Segmentation fault
Segmentation fault
ca-certificates 正在安装...
Segmentation fault
Segmentation fault
coreutils-whoami 正在安装...
Segmentation fault
Segmentation fault
php7 正在安装...
Segmentation fault
Segmentation fault
php7-cgi 正在安装...
Segmentation fault
Segmentation fault
php7-cli 正在安装...
Segmentation fault
Segmentation fault
php7-fastcgi 正在安装...
Segmentation fault
Segmentation fault
php7-fpm 正在安装...
Segmentation fault
Segmentation fault
php7-mod-mysqli 正在安装...
Segmentation fault
Segmentation fault
php7-mod-pdo 正在安装...
Segmentation fault
Segmentation fault
php7-mod-pdo-mysql 正在安装...
Segmentation fault
Segmentation fault
nginx-extras 正在安装...
Segmentation fault
Segmentation fault
mariadb-server 正在安装...
Segmentation fault
Segmentation fault
mariadb-server-extra 正在安装...
Segmentation fault
Segmentation fault
mariadb-client 正在安装...
Segmentation fault
Segmentation fault
mariadb-client-extra 正在安装...
Segmentation fault
Segmentation fault
wget 正在安装...
Segmentation fault
Segmentation fault
unzip 正在安装...
Segmentation fault
Segmentation fault
grep 正在安装...
Segmentation fault
Segmentation fault
sed 正在安装...
Segmentation fault
Segmentation fault
tar 正在安装...
Segmentation fault
Segmentation fault
ca-certificates 正在安装...
Segmentation fault
Segmentation fault
coreutils-whoami 正在安装...
Segmentation fault
Segmentation fault
php7 正在安装...
Segmentation fault
Segmentation fault
php7-cgi 正在安装...
Segmentation fault
Segmentation fault
php7-cli 正在安装...
Segmentation fault
Segmentation fault
php7-fastcgi 正在安装...
Segmentation fault
Segmentation fault
php7-fpm 正在安装...
Segmentation fault
Segmentation fault
php7-mod-mysqli 正在安装...
Segmentation fault
Segmentation fault
php7-mod-pdo 正在安装...
Segmentation fault
Segmentation fault
php7-mod-pdo-mysql 正在安装...
Segmentation fault
Segmentation fault
nginx-extras 正在安装...
Segmentation fault
Segmentation fault
mariadb-server 正在安装...
Segmentation fault
Segmentation fault
mariadb-server-extra 正在安装...
Segmentation fault
Segmentation fault
mariadb-client 正在安装...
Segmentation fault
Segmentation fault
mariadb-client-extra 正在安装...
Segmentation fault

**Comment by monlor** [comment]
小米部分路由器无法安装，建议手动尝试，反馈给我。

**Comment by gm-fire** [comment]
> 小米部分路由器无法安装，建议手动尝试，反馈给我。

不熟悉命令行,请问该如何手动操作?
