### ISSUE TITLE
有文档说明吗？

### ISSUE THREAD

**Issue by abcfy2** [monlor/MIXBOX#47]
比如安装完毕之后，我在交互式界面安装了插件，但是很多配置项简直一脸懵逼啊。

比如aria2的web界面访问路径是什么？ss的那几种模式有什么区别？DNS重定向功能是干什么用的？怎么配置？

这些插件和配置功能如果能有一些详细的文档说明就好了。

**Comment by monlor** [comment]
暂时还木有，可能以后会做web，所以现在这个先用用
