### ISSUE TITLE
kcptun在小米路由器R2D无法启用

### ISSUE THREAD

**Issue by abcfy2** [monlor/MIXBOX#49]
运行之后进程没启动，手工运行kcptun直接提示core dump。疑似需要单独用小米工具链重新编译。

我试过从官方下载armv7的版本，一样运行就提示core dump

**Comment by abcfy2** [comment]
google了一下，原因是小米的那个arm7 CPU不支持浮点，因此要改用arm5架构，从官网下载了一个arm5的kcptun就OK了，下一版考虑提交PR解决

**Comment by monlor** [comment]
R3D是支持的，不过可以都用arm5版的，欢迎提交pr
