### ISSUE TITLE
kcptun的使用方式错误

### ISSUE THREAD

**Issue by abcfy2** [monlor/MIXBOX#51]
CLI配置说明写了kcptun要求和ss在一台服务器上，否则无法启用。这个说法其实是错误的，而且使用方式也是错误的。

按理说应该是这样的连接方式:

```
路由器ss-local -----> 路由器kcptun ----> 服务器kcptun -----> 服务器ssserver
```

但是这个即使将kcptun和ssserver指向同一台服务器，依旧没有使用kcptun加速，配置没变。按理说应该是将ss.conf的服务器配置改为`127.0.0.1:11183`这个地址才对，抽空提交下PRJ解决下吧。

**Comment by abcfy2** [comment]
在我本地已经改的差不多了，再测试一下就考虑提交PR。

原理是kcp启动之后判断启动成功，就将ss服务器指向kcp的本地地址`127.0.0.1:11183`

**Comment by monlor** [comment]
恩恩，我可能搞错了:-)
