### ISSUE TITLE
如何手动/自动更新SS插件的gfwlist

### ISSUE THREAD

**Issue by COBBNELSON** [monlor/MIXBOX#54]
因为自带的那些gfwlist是过时的

**Comment by abcfy2** [comment]
我看ss插件会添加一个定时任务，那个定时任务本来就会更新gfwlist

**Comment by homeyone** [comment]
这个文件在哪里？我选择黑名单模式 直接导致所有网站都无法访问。锅内也不可以。但是选择白名单好多正常能访问的网站也会被扶墙出去，影响速度。

**Comment by melote** [comment]
我的小米路由器HD也无法使用黑名单模式，不知道怎么回事，白名单可以用
