### ISSUE TITLE
可否增加minidlna的插件？

### ISSUE THREAD

**Issue by kl002** [monlor/MIXBOX#57]
家里有些音视频设备只支持dlna的协议，如果能在路由器上加一个dlna的服务器，然后共享路由器硬盘里边的音视频文件就很方便了。

**Comment by abcfy2** [comment]
小米官方插件就有DLAN啊

**Comment by netputer** [comment]
@abcfy2 我是最近新买的小米路由器 Pro，只有 SAMBA 没有 DLNA

**Comment by kl002** [comment]
@abcfy2 小米路由器hd版里边是有DLNA的，但是pro版本是没有的。

**Comment by monlor** [comment]
已添加`DMS`用于`DLNA`，功能是否正常待测试
