### ISSUE TITLE
whitelist

### ISSUE THREAD

**Issue by updater1234** [monlor/MIXBOX#59]
请问，whitelist支持添加ip段吗？

**Comment by abcfy2** [comment]
看了下源码和配置文件，应该是只支持域名和单一ip

**Comment by updater1234** [comment]
那希望能够尽快支持ip端，毕竟单个ip的效率很低。

**Comment by updater1234** [comment]
但奇怪的是chnroute.txt这个文件却是使用Ip段。

**Comment by updater1234** [comment]
从ss_rule_update.sh来看chnroute.txt文件是用来白名单分流的。
