### ISSUE TITLE
kcptum的一个BUG

### ISSUE THREAD

**Issue by sjkgames** [monlor/MIXBOX#60]
@monlor @abcfy2 
 @今晚有幸安装了monlor大佬的mixbox，兴奋之余鼓捣了一下酸酸乳和Kcptun，却一直发现有一个开启Kcptun后无法进程无法启动，后看了@abcfy2 大佬写的kcptum错误的帖子，更新了插件，仍然不行，鼓捣了半宿，发现了一个重大bug。
出现位置，配置kcptun后剩余一些不必要的配置，是否继续？[1/0] 1
按道理后面配置是默认不用修改的，我也就一路回车过去了，但是一直无法进程无法启动，
直到我继续了不必要的配置，发现里面有一条的默认值有误，就是下面这条。
请输入加速kcp接收窗口(--rcvwnd)[回车即1024]：
实际的Kcp接受窗口默认值应为512，但mixbox里的kcptum默认值为1024，
这个值与正常默认值不匹配，导致进程无法开启。
算不上是大BUG，但可能会给新手带来困扰。往大佬修正一下这个bug！
一只苦逼的产品狗

**Comment by cloudtuotuo** [comment]
昨天晚上我的R1D升级了SSR，然后服务就一直无法启动，后来在配置时，进入了高级配置，选择关闭kcptun，就可以启动了，应该是楼主提到的问题

**Comment by abcfy2** [comment]
这里的默认配置是前人留下的，我没改过这里，唯一动过的是`nocomp`，还原到kcptun默认的`false`，我这边倒是可以启动。你能确认下是进程无法启动，还是启动之后无法连接服务端？日志有什么错误信息吗？另外如果之前旧版本升级上来的，应该会保留旧版本的配置才对，这里的默认配置不会影响启动，@cloudtuotuo 你的应该不是一个问题

**Comment by abcfy2** [comment]
我确认了下，的确`rcvwnd`默认设置是`512`，我发现我这边设置`1024`一样可以正常运行。另外如果你那边是进程直接就无法运行，那么应该不是参数配置的问题，而是进程根本就没有启动。

确认下以下命令:

```bash
ps | grep kcptun
```

看看有没有`kcptun`进程在运行，如果有进程运行，说明是其他重要的参数配置不正确导致连不上服务端，如:
- `key`参数是连接密码，这个必须跟服务端保持一致，如果为空，默认是`it's a secrect`，但是`mbdb`目前不支持有特殊字符的情况，如果这个参数不设置，则为空。所以你的服务器必须手工指定一个`key`，并且不能带有空格，引号这种特殊字符，然后在`mixbox`交互界面重新设置
- `dscp`参数有点类似于wifi信道的意思，必须跟服务端保持一致方可连接
- `mode`必须跟服务端保持一致
- `crypt`必须跟服务端保持一致
- `nocomp`必须跟服务端保持一致

如果连进程都看不到，说明是启动就有问题，检查下`/etc/mixbox/var/log/kcptun.log`有误异常崩溃的日志。如果没有，手工运行下kcptun，看看终端是否有输出异常信息:

```bash
eval `mbdb export shadowsocks`
/etc/mixbox/apps/shadowsocks/bin/kcptun \
            --localaddr=127.0.0.1:11183 \
            --remoteaddr=$ss_kcp_node:$ss_kcp_port \
            --key=$ss_kcp_password \
            --crypt=$ss_kcp_crypt \
            --mode=$ss_kcp_mode \
            --mtu=$ss_kcp_mtu \
            --sndwnd=$ss_kcp_sndwnd \
            --rcvwnd=$ss_kcp_rcvwnd \
            --conn=$ss_kcp_conn \
            --nocomp=$ss_kcp_nocomp \
            --dscp=$ss_kcp_dscp \
            --sockbuf=$ss_kcp_sockbuf \
            --smuxbuf=$ss_kcp_smuxbuf \
            $ss_kcp_config
```

看看终端有没有什么错误信息？

**Comment by cloudtuotuo** [comment]
当修改配置后出现下面的提示，就会无法启动

【ShadowSocks】: 关闭ss主进程...
【ShadowSocks】: 删除nat-start触发...
【ShadowSocks】: 清除iptables规则...
**【ShadowSocks】: 未配置kcp加速节点，不启用kcp！**
【ShadowSocks】: 创建节点配置文件...
【ShadowSocks】: 启动ss主进程(xxxxx)...
【ShadowSocks】: 创建ipset规则...
【ShadowSocks】: 加载iptables的nat规则...
【ShadowSocks】: 添加国外黑名单规则...
【ShadowSocks】: 加载ACL规则:[全部主机]代理模式为:[科学上网]
【ShadowSocks】: 启动ss-local本地socks5代理...
【ShadowSocks】: 开启dns2socks进程...
【ShadowSocks】: 添加nat-start触发事件...
【ShadowSocks】: 启动shadowsocks服务完成，启动失败可查看日志或多次重试！

然后在高级设置中：

是否启动shadowsocks的kcptun加速(需要服务端支持)[1/0] [回车即1]：0

【ShadowSocks】: 关闭ss主进程...
【ShadowSocks】: 删除nat-start触发...
【ShadowSocks】: 清除iptables规则...
【ShadowSocks】: 创建节点配置文件...
【ShadowSocks】: 启动ss主进程(xxxx)...
【ShadowSocks】: 创建ipset规则...
【ShadowSocks】: 加载iptables的nat规则...
【ShadowSocks】: 添加国外黑名单规则...
【ShadowSocks】: 加载ACL规则:[全部主机]代理模式为:[科学上网]
【ShadowSocks】: 启动ss-local本地socks5代理...
【ShadowSocks】: 开启dns2socks进程...
【ShadowSocks】: 添加nat-start触发事件...
【ShadowSocks】: 启动shadowsocks服务完成，启动失败可查看日志或多次重试！

服务就正常启动了

**Comment by abcfy2** [comment]
@cloudtuotuo 
这里的脚本我确认了一下，出现`未配置kcp加速节点，不启用kcp！`的提示说明你启用了kcp，但是没有添加kcp服务节点才会出现这个提示。出现这个提示应该是不启用kcptun的，也不会修改ss的配置。你能确认下是否是这样的逻辑?

```bash
ps | grep shadowsocks  # 应该可以看到shadowsocks的几个进程
ps | grep kcptun  # kcptun进程应该不启动
```

```bash
# 这个输出你不用贴出来，里面会包含你的ssr服务器的连接信息
# 里面的server和server_port应该指向你的ssr服务器，而不是127.0.0.1:11183
cat /etc/mixbox/apps/shadowsocks/config/ssr.conf
```

**Comment by cloudtuotuo** [comment]
### ssr服务正常启动状态下的进程情况

root@XiaoQiang:~# ps | grep shadowsocks
17407 root      1700 S    /etc/mixbox/apps/shadowsocks/bin/ssr-redir -b 0.0.0.
17484 root      1152 S    /etc/mixbox/apps/shadowsocks/bin/ssr-local -c /etc/m
17487 root     25976 S    /etc/mixbox/apps/shadowsocks/bin/dns2socks 127.0.0.1
22626 root      1572 S    grep shadowsocks
root@XiaoQiang:~# ps | grep kcptun
22635 root      1572 S    grep kcptun

### 修改配置：
是否启动shadowsocks的kcptun加速(需要服务端支持)[1/0] [回车即0]：1

ssr服务没有正常启动，进程情况：
root@XiaoQiang:/# ps | grep shadowsocks
26713 root      1080 S    /etc/mixbox/apps/shadowsocks/bin/ssr-redir -b 0.0.0.
26797 root      1088 S    /etc/mixbox/apps/shadowsocks/bin/ssr-local -c /etc/m
26800 root      9584 S    /etc/mixbox/apps/shadowsocks/bin/dns2socks 127.0.0.1
28614 root      1572 S    grep shadowsocks
root@XiaoQiang:/# ps | grep kcptun
28620 root      1572 S    grep kcptun

只有在高级配置中关闭了kcptun，服务才能正常启动

ps
因为之前的ssr都是正常的，昨天晚上看到有更新提示，就顺手升级了，结果就出现无法启动的问题
曾经尝试过卸载ssr插件，然后重新安装，但也是无法启动
说明kcptun在这两种情况之下，都被默认开启了，虽然其配置是空的
又因为kcptun配置是空的，所以导致了错误
但这里的问题是：系统既然提示了 未配置kcp加速节点，不启用kcp！，但是为何又会导致了错误呢。。。

**Comment by abcfy2** [comment]
从你的输出来看，都没有启动`kcptun`，检查下`cat /etc/mixbox/apps/shadowsocks/config/ssr.conf`配置

如果kcptun没启动，应该是不会改ss服务端的地址指向kcptun地址才对
