### ISSUE TITLE
shadowsocks能否增加自动订阅更新？

### ISSUE THREAD

**Issue by homeyone** [monlor/MIXBOX#64]
shadowsocks订阅不会自动更新，失效后也不会自动再去获取新的订阅信息。重启路由器后shadowsocks默认又停止启动，这样一来就变成和手动添加没区别了~R3P路由器

**Comment by homeyone** [comment]
0 6 * * * /extdisks/sda1/mixbox/apps/shadowsocks/scripts/shadowsocks.sh restart #mixbox-cru
虽然找到了这一条 但是似乎没执行？
自己再好好研究研究，也感谢作者的辛苦付出

**Comment by homeyone** [comment]
ipset v6.20.1: Error in line 4627: The set with the given name does not exist
哎~还是搞不好，期待作者指点吧

**Comment by tedyye** [comment]
同问，等大神解决

**Comment by monlor** [comment]
每6小时会更新一次，可以看看日志：`cat /tmp/messages`
