### ISSUE TITLE
filebrowser启动失败

### ISSUE THREAD

**Issue by updater1234** [monlor/MIXBOX#65]
日志：
root@XiaoQiang:/etc/mixbox/var/log# cat filebrowser.log 
Error: unknown shorthand flag: 's' in -s
Usage:
  filebrowser [flags]
  filebrowser [command]

Available Commands:
  cmds        Command runner management utility
  config      Configuration management utility
  hash        Hashes a password
  help        Help about any command
  rules       Rules management utility
  upgrade     Upgrades an old configuration
  users       Users management utility
  version     Print the version number

Flags:
  -a, --address string    address to listen on (default "127.0.0.1")
  -b, --baseurl string    base url
  -t, --cert string       tls certificate
  -c, --config string     config file path
  -d, --database string   database path (default "./filebrowser.db")
  -h, --help              help for filebrowser
  -k, --key string        tls key
  -l, --log string        log output (default "stdout")
      --noauth            use the noauth auther when using quick setup
      --password string   hashed password for the first user when using quick config (default "admin")
  -p, --port string       port to listen on (default "8080")
  -r, --root string       root to prepend to relative paths (default ".")
      --username string   username for the first user when using quick config (default "admin")

Use "filebrowser [command] --help" for more information about a command.

2019/05/26 02:39:36 unknown shorthand flag: 's' in -s
希望开发者能尽早修复这个bug。

**Comment by ghjzeus** [comment]
你把脚本中的 -s 改成 -r 试试

**Comment by lleheaven** [comment]
-s 改成 -r  ，我启动了，但是页面仍然访问不到，不知道和我把R2D设置为有线中继是否有关， 然后我又把 那个 sh脚本 参数后面又 加了 -a 192.168.2.xxxx（路由器内网地址） 保存重启就可以访问到了

**Comment by monlor** [comment]
我之前用的`arm`版的`filebrowser`没有这个问题，我更新程序看一下
