### ISSUE TITLE
昨天突然列表里的插件全部丢失

### ISSUE THREAD

**Issue by xyphllipyx** [monlor/MIXBOX#70]
昨天我更新了下梯子订阅，然后再更新一般的过程插件直接提示没了，然后所有已安装插件全部停止运行并逐个自动删除，然后我重启了下再进连续报了三个uci错误后进去列表什么的都空了，只能卸载重新安装，现在的话里面的插件又全消失了，而且路由器能看到拨号成功但ping不通任何网站了，也不能上网，怎么解决？

**Comment by monlor** [comment]
这个问题很奇怪，没有遇到过，现在有复现过么
