### ISSUE TITLE
打开SS白名单，无法访问twitter，reddit

### ISSUE THREAD

**Issue by formalbyte** [monlor/MIXBOX#74]
设备：R1D
版本：0.0.6

安装 ss，设置使用白名单，无法访问大多数本墙的网站，比如twitter，google，reddit。
但黑名单工作正常。

请问白名单需要什么特殊设置吗？
非常感谢。

**Comment by formalbyte** [comment]
Monlor的时候白名单是可以工作的

**Comment by monlor** [comment]
#72
