### ISSUE TITLE
httpfile配置逻辑错误

### ISSUE THREAD

**Issue by wutaijieing** [monlor/MIXBOX#79]
配置完httpfile之后的文件路径为 apps/httpfile/config
但是安装的时候apps/httpfile/config是文件夹路径
所以配置完成后config覆盖了config文件夹，导致mixbox.conf这些文件丢失，无法再次配置

**Comment by fsnhljz** [comment]
怎么可以解决啊

**Comment by monlor** [comment]
感谢，已修复，正在发布
