### ISSUE TITLE
fastdick无法vim编辑配置文件

### ISSUE THREAD

**Issue by a1768623020** [monlor/MIXBOX#8]
[迅雷快鸟，快带提速工具]
启动fastdick服务[1/0] [回车即1]：1
[请按https://github.com/fffonion/Xunlei-Fastdick这里的教程运行swjsq.py并找到运行成功后生成的swjsq_wget.sh文件，复制其所 有内容编辑到配置里]
修改fastdick配置(将开始使用vim编辑快鸟运行脚本)？[1/0]1
[提示]按i开始编辑，编辑完按ESC键再按:wq即可保存退出[注意冒号]
清空文件之后再编辑？[1/0]0
/etc/mixbox/bin/mixbox: line 1: vim: not found
请输入fastdick外网访问配置[1/0][回车即1]：
【FastDick】: 正在停止fastdick服务...
【FastDick】: 正在启动fastdick服务...
【FastDick】: 启动fastdick服务完成！

路由器R3G

**Comment by monlor** [comment]
额，3G没有vim么。。
