### ISSUE TITLE
Aliddns插件失效

### ISSUE THREAD

**Issue by songwu1230** [monlor/MIXBOX#83]
小米路由R2D，Aliddns插件配置完成中间无报错，无提示，但是就是没有配置成功，阿里云控制台没有看到IP地址更新。怒跪求解～

**Comment by monlor** [comment]
这个问题有解决么

**Comment by monlor** [comment]
如果没有解决的话再提，我先关闭问题了

**Comment by 3610cn** [comment]
我也是这样的 ，小米路由R2D
