### ISSUE TITLE
R2D配置文件测试失败。。。

### ISSUE THREAD

**Issue by AlexWang026** [monlor/MIXBOX#85]
![WechatIMG44](https://user-images.githubusercontent.com/56222684/66268920-c3c79c80-e874-11e9-8036-21a2c5488f56.jpeg)
启动代理为v2ray，测试配置文件
配置文件测试失败

**Comment by ishare20** [comment]
你这是空间不足，换个位置装，先df -h

**Comment by fsandrew** [comment]
安装mixbox时安装目录无按照提示选择
