### ISSUE TITLE
KCP加速，不知道怎么回事，无论怎么设置都不成功

### ISSUE THREAD

**Issue by wangchuanyes** [monlor/MIXBOX#86]
KCP加速，不知道怎么回事，无论怎么设置都不成功。
能否改成以一键粘贴所有参数的形式设置KCP呢？
key=wangchuan;crypt=none;mode=fast;mtu=1350;sndwnd=512;rcvwnd=512;datashard=10;parityshard=3;dscp=0;nocomp

**Comment by monlor** [comment]
使用的是0.1.1版本的ss插件么
