### ISSUE TITLE
FATAL: kernel too old 

### ISSUE THREAD

**Issue by jovelang** [monlor/MIXBOX#87]
问题1：
安装 entware 后安装 ONMP 提示我FATAL: kernel too old 
安装 entware 后使用zerotier 添加 ID 时 也提示FATAL: kernel too old 

问题2：使用了 AliDDNS 加入成功，但是无法访问。但是用ngrok可以。不知道原因

我是小米路由器 R3

**Comment by monlor** [comment]
工具箱的`Entware`不支持`R3`，我没有该设备，你可以尝试用网上的教程安装`Entware`，成功了可以告诉我。
