### ISSUE TITLE
请教自定义黑名单通配格式规则

### ISSUE THREAD

**Issue by lslzl3000** [monlor/MIXBOX#92]
如希望 abc.com 名下所有子域名 (a.abc.com, b.abc.com, xxx.abc.com,...) 都走代理如何输入？

测试目前必须每个域名单独书写，写 `*.abc.com` 或 `||abc.com` 不成功，但子域名太多了，不可能一个一个写，请教这个`customize_black.conf` 到底如何工作的

**Comment by monlor** [comment]
试试 `.abc.com`

**Comment by lslzl3000** [comment]
试过 `.abc.com` ，其实就是 `*.abc.com` 的简写，经过我的测试，应该是使用ipv6的关系，如果路由不启用v6，本身的gfwlist和黑名单都有用，但启用v6后大量通配域名网站就不行了，必须添加每个单独子域名才行。
我猜跟v6 dns有关吧？请研究一下，谢谢
