### ISSUE TITLE
v2ray十万火急啊

### ISSUE THREAD

**Issue by lovewhogx** [monlor/MIXBOX#94]
跪求作者放V2ray独立插件，然后添加订阅功能。

**Comment by iecctc** [comment]
我也支持一下，目前使用上好像还是有问题。ws+tls+cdn模式，手机直接设置可用，但是在路由器上却不行，R1D。

**Comment by nfeuism** [comment]
同ws+tls无法使用

**Comment by monlor** [comment]
v2ray暂时不更新
