### ISSUE TITLE
frps无法启动

### ISSUE THREAD

**Issue by blackhumors** [monlor/MIXBOX#97]
frps在工具箱配置完还是显示未启动，大佬看看什么问题

**Comment by monlor** [comment]
建议看看日志`cat /var/log/frps.log`

**Comment by blackhumors** [comment]
没找到日志文件，我的小米r1d，上面的路径里没有frps.log

**Comment by blackhumors** [comment]
root@XiaoQiang:/userdisk# find / -name "frps.log"
/data/etc/mixbox/var/log/frps.log
/etc/mixbox/var/log/frps.log
root@XiaoQiang:/userdisk# cat /data/etc/mixbox/var/log/frps.log
root@XiaoQiang:/userdisk# cat /etc/mixbox/var/log/frps.log

**Comment by blackhumors** [comment]
你发的路径没有对应log文件，我只找到以上2个frps.log文件，但是都是空的

**Comment by monlor** [comment]
`ps | grep frps` 执行这个命令能找到frp进程就表明启动了，之前状态判断可能有点问题，已经解决了

**Comment by blackhumors** [comment]
thanks

**Comment by blackhumors** [comment]
我发现启动的时候选择修改配置永远启动不了，选择不改即可启动，大佬再看看呢
